# Banco del crucigrama: (PALABRA sin tildes, pista, categoría)
B = [
 # --- Antiguo Testamento: personas ---
 ("ADAN", "Primer hombre, según el Génesis", "Biblia"),
 ("EVA", "Primera mujer, según el Génesis", "Biblia"),
 ("CAIN", "Hijo de Adán y Eva que mató a su hermano", "Biblia"),
 ("ABEL", "Hermano de Caín, pastor de ovejas", "Biblia"),
 ("NOE", "Construyó el arca por pedido de Dios", "Biblia"),
 ("ABRAHAM", "Padre en la fe: dejó su tierra por pedido de Dios", "Biblia"),
 ("SARA", "Esposa de Abraham y madre de Isaac", "Biblia"),
 ("ISAAC", "Hijo de Abraham y Sara", "Biblia"),
 ("JACOB", "Hijo de Isaac, también llamado Israel", "Biblia"),
 ("ESAU", "Hermano mellizo de Jacob", "Biblia"),
 ("MOISES", "Guió al pueblo de Israel en la salida de Egipto", "Biblia"),
 ("AARON", "Hermano de Moisés", "Biblia"),
 ("JOSUE", "Sucesor de Moisés que entró en la Tierra Prometida", "Biblia"),
 ("SANSON", "Juez de Israel de fuerza extraordinaria", "Biblia"),
 ("RUT", "Moabita fiel a su suegra Noemí", "Biblia"),
 ("SAMUEL", "Respondió: «Habla, porque tu servidor escucha»", "Biblia"),
 ("SAUL", "Primer rey de Israel", "Biblia"),
 ("DAVID", "Pastor que venció a Goliat y llegó a rey", "Biblia"),
 ("GOLIAT", "Gigante filisteo vencido con una honda", "Biblia"),
 ("SALOMON", "Rey de Israel famoso por su sabiduría", "Biblia"),
 ("ELIAS", "Profeta llevado al cielo en un carro de fuego", "Biblia"),
 ("ELISEO", "Discípulo y sucesor del profeta Elías", "Biblia"),
 ("ISAIAS", "Profeta: «Un niño nos ha nacido»", "Biblia"),
 ("JEREMIAS", "Profeta llamado desde el seno materno", "Biblia"),
 ("DANIEL", "Profeta arrojado al foso de los leones", "Biblia"),
 ("JONAS", "Profeta que pasó tres días dentro de un gran pez", "Biblia"),
 ("JOB", "Hombre justo que sufrió mucho sin perder la fe", "Biblia"),
 ("TOBIAS", "Joven acompañado en su viaje por el arcángel Rafael", "Biblia"),
 ("ESTER", "Reina que salvó a su pueblo", "Biblia"),
 ("NOEMI", "Suegra de Rut", "Biblia"),
 # --- Nuevo Testamento: personas ---
 ("JESUS", "Nombre que significa «Dios salva»", "Biblia"),
 ("MARIA", "Madre de Jesús", "Biblia"),
 ("JOSE", "Esposo de María y padre adoptivo de Jesús", "Biblia"),
 ("PEDRO", "Apóstol a quien Jesús le dio las llaves del Reino", "Biblia"),
 ("ANDRES", "Hermano de Pedro, también pescador", "Biblia"),
 ("SANTIAGO", "Apóstol, hermano de Juan e hijo de Zebedeo", "Biblia"),
 ("JUAN", "El discípulo amado", "Biblia"),
 ("TOMAS", "Apóstol que no creyó hasta ver las heridas de Jesús", "Biblia"),
 ("MATEO", "Recaudador de impuestos que se hizo apóstol", "Biblia"),
 ("FELIPE", "Apóstol que llevó a Natanael a conocer a Jesús", "Biblia"),
 ("JUDAS", "Apóstol que traicionó a Jesús", "Biblia"),
 ("MATIAS", "Apóstol elegido para reemplazar a Judas", "Biblia"),
 ("PABLO", "Apóstol de los paganos, antes llamado Saulo", "Biblia"),
 ("LUCAS", "Evangelista que también escribió los Hechos", "Biblia"),
 ("MARCOS", "Autor del Evangelio más breve", "Biblia"),
 ("ZAQUEO", "Se subió a un árbol para ver pasar a Jesús", "Biblia"),
 ("LAZARO", "Amigo de Jesús, resucitado en Betania", "Biblia"),
 ("MARTA", "Hermana de Lázaro, atareada en servir", "Biblia"),
 ("NICODEMO", "Fariseo que visitó a Jesús de noche", "Biblia"),
 ("PILATO", "Gobernador romano que condenó a Jesús", "Biblia"),
 ("HERODES", "Rey que buscó al Niño para matarlo", "Biblia"),
 ("ISABEL", "Prima de María y madre de Juan el Bautista", "Biblia"),
 ("ZACARIAS", "Padre de Juan el Bautista", "Biblia"),
 ("SIMEON", "Anciano que tomó a Jesús en brazos en el Templo", "Biblia"),
 ("ANA", "Madre de la Virgen María", "Santos"),
 ("JOAQUIN", "Padre de la Virgen María", "Santos"),
 ("GABRIEL", "Arcángel de la Anunciación", "Biblia"),
 ("MIGUEL", "Arcángel que vence al dragón", "Biblia"),
 ("RAFAEL", "Arcángel que acompañó a Tobías", "Biblia"),
 ("BARTIMEO", "Ciego de Jericó que recuperó la vista", "Biblia"),
 ("ESTEBAN", "Primer mártir cristiano", "Biblia"),
 ("BERNABE", "Compañero de viajes de Pablo", "Biblia"),
 ("TIMOTEO", "Joven discípulo de Pablo, destinatario de dos cartas", "Biblia"),
 ("MAGDALENA", "María ___: primera testigo de la Resurrección", "Biblia"),
 ("BARRABAS", "Preso liberado en lugar de Jesús", "Biblia"),
 ("CAIFAS", "Sumo sacerdote durante el juicio a Jesús", "Biblia"),
 # --- Lugares ---
 ("BELEN", "Ciudad donde nació Jesús", "Biblia"),
 ("NAZARET", "Pueblo donde creció Jesús", "Biblia"),
 ("JERUSALEN", "Ciudad del Templo", "Biblia"),
 ("CANA", "Allí Jesús convirtió el agua en vino", "Biblia"),
 ("JORDAN", "Río donde Jesús fue bautizado", "Biblia"),
 ("GALILEA", "Región del lago donde pescaban los apóstoles", "Biblia"),
 ("EGIPTO", "País del que Moisés sacó al pueblo de Israel", "Biblia"),
 ("SINAI", "Monte donde Moisés recibió los mandamientos", "Biblia"),
 ("TABOR", "Monte de la Transfiguración, según la tradición", "Biblia"),
 ("CALVARIO", "Monte donde crucificaron a Jesús", "Biblia"),
 ("GOLGOTA", "«Lugar de la Calavera»", "Biblia"),
 ("BETANIA", "Pueblo de Lázaro, Marta y María", "Biblia"),
 ("EMAUS", "Pueblo al que iban dos discípulos cuando se les apareció Jesús", "Biblia"),
 ("JERICO", "Ciudad cuyas murallas cayeron", "Biblia"),
 ("BABEL", "Torre de la confusión de las lenguas", "Biblia"),
 ("EDEN", "Jardín donde Dios puso a Adán y Eva", "Biblia"),
 ("ROMA", "Ciudad donde murieron mártires Pedro y Pablo", "Iglesia"),
 ("DAMASCO", "Camino donde se convirtió Pablo", "Biblia"),
 ("CAFARNAUM", "Ciudad junto al lago donde vivió Jesús durante su predicación", "Biblia"),
 ("GETSEMANI", "Huerto donde Jesús rezó antes de ser arrestado", "Biblia"),
 ("LOURDES", "Lugar de Francia donde la Virgen se le apareció a Bernardita", "Santos"),
 ("FATIMA", "Lugar de Portugal donde la Virgen se apareció a tres pastorcitos", "Santos"),
 ("LUJAN", "Basílica de la patrona de la Argentina", "Sagrada"),
 ("GUADALUPE", "Virgen que se le apareció a Juan Diego", "Santos"),
 ("ASIS", "Ciudad de San Francisco y Santa Clara", "Santos"),
 ("CALCUTA", "Ciudad de la India donde sirvió la Madre Teresa", "Santos"),
 # --- Libros y Biblia ---
 ("BIBLIA", "Libro que reúne la Palabra de Dios", "Biblia"),
 ("GENESIS", "Primer libro de la Biblia", "Biblia"),
 ("EXODO", "Libro de la salida de Egipto", "Biblia"),
 ("SALMOS", "Libro de 150 oraciones y cantos", "Biblia"),
 ("PROVERBIOS", "Libro de dichos sabios atribuidos a Salomón", "Biblia"),
 ("HECHOS", "Libro de los ___ de los Apóstoles", "Biblia"),
 ("ROMANOS", "Carta de Pablo a los cristianos de Roma", "Biblia"),
 ("APOCALIPSIS", "Último libro de la Biblia", "Biblia"),
 ("EVANGELIO", "Significa «Buena Noticia»", "Biblia"),
 ("PARABOLA", "Relato breve con el que Jesús enseñaba", "Biblia"),
 ("SALMO", "Canto de oración del libro de David", "Biblia"),
 ("VERSICULO", "Cada numerito en que se divide un capítulo de la Biblia", "Biblia"),
 ("MILAGRO", "Signo extraordinario, como la multiplicación de los panes", "Biblia"),
 ("PROFETA", "Hablaba en nombre de Dios al pueblo", "Biblia"),
 ("APOSTOL", "Cada uno de los Doce elegidos por Jesús", "Biblia"),
 ("DISCIPULO", "Seguidor de Jesús", "Biblia"),
 ("MESIAS", "«Ungido»: el que esperaba Israel", "Biblia"),
 ("CRISTO", "«Ungido» en griego", "Biblia"),
 ("EMANUEL", "Nombre que significa «Dios con nosotros»", "Biblia"),
 ("ALIANZA", "Pacto de amor entre Dios y su pueblo", "Biblia"),
 ("PROMESA", "Dios la cumple: la Tierra ___", "Biblia"),
 ("PATRIARCA", "Título de Abraham, Isaac y Jacob", "Biblia"),
 # --- Objetos y símbolos ---
 ("ARCA", "Barco de Noé", "Biblia"),
 ("MANA", "Alimento del cielo en el desierto", "Biblia"),
 ("CRUZ", "Signo del cristiano", "Fe"),
 ("PAN", "Jesús se presentó como el ___ de Vida", "Biblia"),
 ("VINO", "Lo que había en las tinajas de Caná al final", "Biblia"),
 ("AGUA", "Con ella se bautiza", "Sacramentos"),
 ("CORDERO", "«Este es el ___ de Dios»", "Biblia"),
 ("PALOMA", "Ave que simboliza al Espíritu Santo", "Fe"),
 ("ESTRELLA", "Guió a los Magos hasta Belén", "Biblia"),
 ("PESEBRE", "Lugar donde acostaron al Niño Jesús", "Biblia"),
 ("OLIVO", "Árbol del monte donde rezó Jesús", "Biblia"),
 ("TEMPLO", "Casa de Dios en Jerusalén", "Biblia"),
 ("ALTAR", "Mesa donde se celebra la Eucaristía", "Liturgia"),
 ("CALIZ", "Copa donde se consagra el vino", "Liturgia"),
 ("PATENA", "Platito donde se coloca la hostia", "Liturgia"),
 ("HOSTIA", "Pan consagrado en la misa", "Liturgia"),
 ("SAGRARIO", "Lugar donde se guarda la Eucaristía", "Liturgia"),
 ("CUSTODIA", "Objeto dorado para exponer el Santísimo", "Liturgia"),
 ("ROSARIO", "Oración con cuentas y misterios", "Fe"),
 ("INCIENSO", "Uno de los regalos de los Magos; perfuma la oración", "Liturgia"),
 ("CIRIO", "Vela grande que se enciende en la Vigilia pascual", "Liturgia"),
 ("AMBON", "Lugar desde donde se proclama la Palabra", "Liturgia"),
 ("ESTOLA", "Prenda del sacerdote que cuelga sobre los hombros", "Liturgia"),
 ("CASULLA", "Vestidura que el sacerdote usa para celebrar la misa", "Liturgia"),
 ("MITRA", "Gorro alto del obispo", "Iglesia"),
 ("BACULO", "Bastón del obispo, como de pastor", "Iglesia"),
 ("CAMPANA", "Llama a misa desde el campanario", "Liturgia"),
 ("CENIZA", "Se impone el primer día de Cuaresma", "Liturgia"),
 ("RAMOS", "Domingo de ___: entrada de Jesús en Jerusalén", "Liturgia"),
 ("ESPINAS", "Corona que le pusieron a Jesús", "Biblia"),
 ("CLAVOS", "Con ellos fijaron a Jesús en la cruz", "Biblia"),
 ("LANZA", "Con ella un soldado abrió el costado de Jesús", "Biblia"),
 ("SEPULCRO", "Lo encontraron vacío el domingo", "Biblia"),
 ("LLAVES", "Jesús se las dio a Pedro", "Biblia"),
 ("BARCA", "Desde ella Jesús calmó la tormenta", "Biblia"),
 ("RED", "Herramienta de los pescadores", "Biblia"),
 ("TALENTOS", "Parábola de los que hicieron rendir lo recibido", "Biblia"),
 ("SEMILLA", "Parábola del sembrador: cae en distintos terrenos", "Biblia"),
 ("MOSTAZA", "Semilla pequeña que se convierte en árbol", "Biblia"),
 ("LEVADURA", "Hace fermentar toda la masa", "Biblia"),
 ("SAL", "«Ustedes son la ___ de la tierra»", "Biblia"),
 ("LUZ", "«Ustedes son la ___ del mundo»", "Biblia"),
 ("LAMPARA", "«Tu palabra es una ___ para mis pasos»", "Biblia"),
 ("PERLA", "Un comerciante vendió todo para comprar una de gran valor", "Biblia"),
 ("TESORO", "Escondido en un campo, según una parábola", "Biblia"),
 ("OVEJA", "El buen pastor deja las 99 para buscarla", "Biblia"),
 ("PASTOR", "«Yo soy el buen ___»", "Biblia"),
 ("VID", "«Yo soy la ___, ustedes los sarmientos»", "Biblia"),
 ("HIGUERA", "Árbol que Jesús encontró sin frutos", "Biblia"),
 ("ZARZA", "Ardía sin consumirse frente a Moisés", "Biblia"),
 ("ESCALERA", "Jacob soñó con una que llegaba al cielo", "Biblia"),
 ("HONDA", "Arma con la que David venció a Goliat", "Biblia"),
 ("ARPA", "Instrumento que tocaba David", "Biblia"),
 ("TUNICA", "Prenda de Jesús que los soldados sortearon", "Biblia"),
 ("TABLAS", "Piedras de los diez mandamientos", "Biblia"),
 ("ARCOIRIS", "Signo de la alianza con Noé", "Biblia"),
 ("MIRRA", "Regalo de los Magos junto con el oro y el incienso", "Biblia"),
 ("ORO", "Uno de los regalos de los Magos", "Biblia"),
 # --- Sacramentos y liturgia ---
 ("BAUTISMO", "Sacramento que nos hace hijos de Dios", "Sacramentos"),
 ("EUCARISTIA", "Significa «acción de gracias»", "Sacramentos"),
 ("PERDON", "Lo recibimos en la Reconciliación", "Sacramentos"),
 ("UNCION", "Sacramento de los enfermos", "Sacramentos"),
 ("MATRIMONIO", "Sacramento del amor entre esposos", "Sacramentos"),
 ("ORDEN", "Sacramento de los sacerdotes", "Sacramentos"),
 ("SACRAMENTO", "Son siete: signos de la gracia", "Sacramentos"),
 ("CONFESION", "Otro nombre de la Reconciliación", "Sacramentos"),
 ("MISA", "Celebración de la Eucaristía", "Liturgia"),
 ("COMUNION", "Recibir a Jesús en la Eucaristía", "Liturgia"),
 ("ADORACION", "Rezar frente al Santísimo expuesto", "Liturgia"),
 ("CREDO", "Oración que resume la fe", "Fe"),
 ("AMEN", "Significa «así es»", "Fe"),
 ("ALELUYA", "Grito de alegría pascual: «alaben al Señor»", "Liturgia"),
 ("HOSANNA", "Gritaba la gente en la entrada a Jerusalén", "Biblia"),
 ("GLORIA", "«___ a Dios en el cielo»", "Liturgia"),
 ("ANGELUS", "Oración del mediodía sobre la Anunciación", "Fe"),
 ("AVEMARIA", "Oración que empieza con el saludo del ángel", "Fe"),
 ("MAGNIFICAT", "Canto de María: «Mi alma canta la grandeza del Señor»", "Biblia"),
 ("BENDICION", "La da el sacerdote al final de la misa", "Liturgia"),
 ("HOMILIA", "Prédica del sacerdote después del Evangelio", "Liturgia"),
 ("LITURGIA", "Celebración pública de la Iglesia", "Liturgia"),
 ("CUARESMA", "Cuarenta días de preparación para la Pascua", "Liturgia"),
 ("ADVIENTO", "Tiempo de espera antes de Navidad", "Liturgia"),
 ("NAVIDAD", "Celebramos el nacimiento de Jesús", "Liturgia"),
 ("PASCUA", "Fiesta de la Resurrección", "Liturgia"),
 ("PENTECOSTES", "Venida del Espíritu Santo", "Liturgia"),
 ("EPIFANIA", "Fiesta de los Reyes Magos", "Liturgia"),
 ("ASCENSION", "Jesús sube al cielo", "Liturgia"),
 ("ASUNCION", "María llevada al cielo en cuerpo y alma", "Liturgia"),
 ("VIGILIA", "Celebración de la noche del Sábado Santo", "Liturgia"),
 ("PROCESION", "Caminar rezando detrás de una imagen o del Santísimo", "Liturgia"),
 ("NOVENA", "Nueve días de oración", "Fe"),
 ("AYUNO", "Pilar de la Cuaresma junto a la oración y la limosna", "Fe"),
 ("LIMOSNA", "Ayuda a los necesitados, pilar de la Cuaresma", "Fe"),
 ("PENITENCIA", "Signo de conversión que se cumple después de confesarse", "Sacramentos"),
 ("PADRINO", "Acompaña en el Bautismo o la Confirmación", "Sacramentos"),
 ("CRISMA", "Óleo perfumado de la Confirmación", "Sacramentos"),
 ("MORADO", "Color litúrgico de Adviento y Cuaresma", "Liturgia"),
 ("BLANCO", "Color litúrgico de Pascua y Navidad", "Liturgia"),
 ("ROJO", "Color litúrgico de Pentecostés y los mártires", "Liturgia"),
 ("VERDE", "Color litúrgico del Tiempo Ordinario", "Liturgia"),
 # --- Fe y virtudes ---
 ("FE", "Virtud teologal: creer en Dios", "Fe"),
 ("ESPERANZA", "Virtud teologal que confía en las promesas de Dios", "Fe"),
 ("CARIDAD", "La más grande de las virtudes teologales", "Fe"),
 ("PRUDENCIA", "Virtud cardinal de decidir bien", "Fe"),
 ("JUSTICIA", "Virtud cardinal de dar a cada uno lo suyo", "Fe"),
 ("FORTALEZA", "Virtud y don para no rendirse ante lo difícil", "Fe"),
 ("TEMPLANZA", "Virtud cardinal de la moderación", "Fe"),
 ("SABIDURIA", "Primer don del Espíritu Santo", "Fe"),
 ("PIEDAD", "Don del Espíritu Santo de amar a Dios como Padre", "Fe"),
 ("CONSEJO", "Don del Espíritu Santo para elegir bien", "Fe"),
 ("HUMILDAD", "Virtud de reconocerse pequeño ante Dios", "Fe"),
 ("PACIENCIA", "«El amor es ___»", "Fe"),
 ("MISERICORDIA", "Amor de Dios que perdona", "Fe"),
 ("PECADO", "Ofensa a Dios y al prójimo", "Fe"),
 ("CONVERSION", "Volver el corazón a Dios", "Fe"),
 ("GRACIA", "Regalo gratuito de Dios", "Fe"),
 ("TRINIDAD", "Padre, Hijo y Espíritu Santo", "Fe"),
 ("ESPIRITU", "___ Santo, tercera persona de la Trinidad", "Fe"),
 ("PADRE", "Primera persona de la Trinidad", "Fe"),
 ("IGLESIA", "Comunidad de los que siguen a Jesús", "Iglesia"),
 ("PAPA", "Sucesor de Pedro", "Iglesia"),
 ("OBISPO", "Pastor de una diócesis", "Iglesia"),
 ("SACERDOTE", "Celebra la misa y perdona los pecados", "Iglesia"),
 ("DIACONO", "Ministro que puede bautizar y proclamar el Evangelio", "Iglesia"),
 ("MONJA", "Religiosa que vive en comunidad", "Iglesia"),
 ("PARROQUIA", "Comunidad de fe de un barrio", "Iglesia"),
 ("CATEDRAL", "Iglesia principal del obispo", "Iglesia"),
 ("BASILICA", "Iglesia de especial importancia, como la de Luján", "Iglesia"),
 ("CAPILLA", "Iglesia pequeña", "Iglesia"),
 ("MONASTERIO", "Casa donde viven monjes", "Iglesia"),
 ("MARTIR", "Da la vida por la fe", "Santos"),
 ("SANTO", "Persona que vive el Evangelio a fondo", "Santos"),
 ("BEATO", "Paso anterior a la canonización", "Santos"),
 ("ANGEL", "Mensajero de Dios", "Fe"),
 ("CIELO", "Destino final: vivir con Dios para siempre", "Fe"),
 ("ALMA", "Lo espiritual de la persona", "Fe"),
 ("CORAZON", "«Allí donde esté tu tesoro, estará también tu ___»", "Biblia"),
 ("AMOR", "«Dios es ___»", "Biblia"),
 ("PAZ", "«Les dejo la ___, les doy mi ___»", "Biblia"),
 ("ALEGRIA", "Fruto del Espíritu; «Alégrense siempre en el Señor»", "Fe"),
 ("VERDAD", "«Yo soy el Camino, la ___ y la Vida»", "Biblia"),
 ("CAMINO", "«Yo soy el ___, la Verdad y la Vida»", "Biblia"),
 ("PALABRA", "«Y la ___ se hizo carne»", "Biblia"),
 ("MANDAMIENTO", "Son diez", "Fe"),
 ("RESURRECCION", "Jesús venció a la muerte", "Fe"),
 ("ANUNCIACION", "El ángel Gabriel visita a María", "Biblia"),
 ("VISITACION", "María va a ver a su prima Isabel", "Biblia"),
 ("TRANSFIGURACION", "Jesús se muestra resplandeciente en el monte", "Biblia"),
 ("PASION", "Sufrimiento de Jesús antes de morir", "Biblia"),
 ("CENACULO", "Sala de la Última Cena", "Biblia"),
 ("SALVADOR", "Título de Jesús: nos rescata del pecado", "Fe"),
 ("REDENTOR", "Jesús, que nos libera con su cruz", "Fe"),
 ("ORACION", "Hablar con Dios", "Fe"),
 ("MISION", "Anunciar a Jesús en todas partes", "Fe"),
 ("RETIRO", "Días de silencio y oración", "Fe"),
 ("CATEQUESIS", "Enseñanza de la fe", "Fe"),
 ("PEREGRINO", "El que camina hacia un santuario", "Fe"),
 ("VOCACION", "Llamado de Dios", "Fe"),
 ("SANTIDAD", "A ella estamos todos llamados", "Fe"),
 ("PROJIMO", "«Amarás a tu ___ como a ti mismo»", "Biblia"),
 ("JUICIO", "El final de los tiempos, según el Credo", "Fe"),
 ("BIENAVENTURANZAS", "«Felices los…»: discurso del monte", "Biblia"),
 # --- Santos ---
 ("AGUSTIN", "Escribió las Confesiones", "Santos"),
 ("MONICA", "Rezó años por la conversión de su hijo Agustín", "Santos"),
 ("TERESITA", "Santa del «caminito»", "Santos"),
 ("KOLBE", "Maximiliano ___: dio la vida en Auschwitz", "Santos"),
 ("FRASSATI", "Pier Giorgio ___: «Verso l'alto»", "Santos"),
 ("ACUTIS", "Carlo ___: el «influencer de Dios»", "Santos"),
 ("BROCHERO", "El Cura Gaucho", "Santos"),
 ("CEFERINO", "Beato hijo de un cacique mapuche", "Santos"),
 ("FRANCISCO", "Santo de Asís, patrono de la ecología", "Santos"),
 ("CLARA", "Santa de Asís, patrona de la televisión", "Santos"),
 ("BOSCO", "Don ___: fundador de los salesianos", "Santos"),
 ("IGNACIO", "Fundador de los jesuitas", "Santos"),
 ("JAVIER", "Francisco ___: misionero en la India y Japón", "Santos"),
 ("FAUSTINA", "Santa de la Divina Misericordia", "Santos"),
 ("BENITO", "Santo del «Ora et labora»", "Santos"),
 ("BERNARDITA", "Vio a la Virgen en Lourdes", "Santos"),
 ("NEWMAN", "Cardenal inglés: «Guíame, luz amable»", "Santos"),
 ("CHARBEL", "Monje ermitaño del Líbano", "Santos"),
 ("ANTONIO", "Santo de Padua, al que se le piden las cosas perdidas", "Santos"),
 ("BAKHITA", "Santa sudanesa que fue esclava", "Santos"),
 ("GIANNA", "Santa médica que dio la vida por su hija", "Santos"),
 ("ROMERO", "Óscar ___: arzobispo mártir de El Salvador", "Santos"),
 ("CATALINA", "Santa de Siena, Doctora de la Iglesia", "Santos"),
 ("SAVIO", "Domingo ___: «Antes morir que pecar»", "Santos"),
 ("VIANNEY", "El Santo Cura de Ars", "Santos"),
 ("DAMIAN", "Santo que sirvió a los enfermos de lepra en Molokai", "Santos"),
 ("ANTULA", "Mama ___: primera santa argentina", "Santos"),
 ("MONICA", "Madre de San Agustín", "Santos"),
 ("FELIPE", "Neri: el santo de la alegría (nombre)", "Santos"),
 ("ROSA", "Santa de Lima, primera santa de América", "Santos"),
 ("MORO", "Tomás ___: patrono de los políticos", "Santos"),
 ("PIO", "Padre ___: fraile con los estigmas", "Santos"),
 ("JUANDIEGO", "Indígena que vio a la Virgen de Guadalupe (todo junto)", "Santos"),
 ("TERESA", "Santa de Ávila y de Calcuta", "Santos"),
 # --- Sagrada ---
 ("FARO", "Grupo de Sagrada de 3er y 4to año", "Sagrada"),
 ("HPP", "Herramientas para perseverar", "Sagrada"),
 ("NAZA", "Así le dicen a Nazaret, el grupo de universitarios", "Sagrada"),
 ("PUENTE", "___ a María: grupo misionero", "Sagrada"),
 ("TUNAS", "Barrio donde misiona Puente a María todas las semanas", "Sagrada"),
 ("RAUCH", "Lugar de la primera misión de Sagrada", "Sagrada"),
 ("NORDELTA", "Barrio de nuestra parroquia", "Sagrada"),
 ("POST", "Grupo que culmina con la consagración a María", "Sagrada"),
 ("CONFIR", "Así le decimos a la Confirmación", "Sagrada"),
 ("SANBOMAZO", "El mejor equipo de fútbol de Sagrada", "Sagrada"),
 ("RIVER", "Equipo del que es hincha el P. Checo", "Sagrada"),
 ("MOTO", "Hobby del P. Augusto: andar en…", "Sagrada"),
 ("CHECO", "Apodo del P. Carlos Avellaneda", "Sagrada"),
 ("AUGUSTO", "Nombre del P. Zampini", "Sagrada"),
 ("PIZZAS", "Adoración y ___: primer miércoles de cada mes", "Sagrada"),
 ("LINIERS", "Desde ahí sale el trayecto más largo a Luján", "Sagrada"),
 ("MORENO", "Trayecto de 35 km a Luján", "Sagrada"),
 ("FAMILIA", "Sagrada ___: nuestra parroquia", "Sagrada"),
 ("JOVENES", "Misa de ___: domingos a las 20:15", "Sagrada"),
 ("ZAMPINI", "Apellido del P. Augusto", "Sagrada"),
 ("AVELLANEDA", "Apellido del P. Checo", "Sagrada"),
 ("COORDINADOR", "Acompaña a un grupo de Confir", "Sagrada"),
 ("CAMPAMENTO", "FARO tiene uno por año", "Sagrada"),
 ("CONVIVENCIA", "FARO tiene cuatro por año", "Sagrada"),
]
