"""Banco del juego «Versículo del día».

Cada versículo: (cita, fragmento textual de El Libro del Pueblo de Dios, palabra oculta, [tres incorrectas]).
El fragmento tiene que ser TEXTUAL: verificar_versiculos.py lo compara con el texto publicado en vatican.va
y avisa si no coincide o si la palabra oculta aparece más de una vez.
"""

# Abreviatura de la cita -> nombre del libro en el índice de vatican.va/archive/ESL0506
LIBROS = {
    "Jn": "EVANGELIO SEGUN SAN JUAN",
    "Mt": "EVANGELIO SEGUN SAN MATEO",
    "Mc": "EVANGELIO SEGUN SAN MARCOS",
    "Lc": "EVANGELIO SEGUN SAN LUCAS",
    "Hch": "HECHOS DE LOS APOSTOLES",
    "Rom": "CARTA A LOS ROMANOS",
    "1 Cor": "PRIMERA CARTA A LOS CORINTIOS",
    "2 Cor": "SEGUNDA CARTA A LOS CORINTIOS",
    "Gál": "CARTA A LOS GALATAS",
    "Flp": "CARTA A LOS FILIPENSES",
    "Col": "CARTA A LOS COLOSENSES",
    "1 Tes": "PRIMERA CARTA A LOS TESALONICENSES",
    "1 Tim": "PRIMERA CARTA A TIMOTEO",
    "2 Tim": "SEGUNDA CARTA A TIMOTEO",
    "Heb": "CARTA A LOS HEBREOS",
    "Sant": "CARTA DE SANTIAGO",
    "1 Pe": "PRIMERA CARTA DE SAN PEDRO",
    "1 Jn": "PRIMERA CARTA DE SAN JUAN",
    "Ap": "APOCALIPSIS",
    "Gn": "GENESIS",
    "Sal": "SALMOS",
    "Is": "ISAIAS",
    "Jer": "JEREMIAS",
    "Prov": "PROVERBIOS",
    "Jos": "JOSUE",
    "1 Sam": "PRIMER LIBRO DE SAMUEL",
    "Ecl": "ECLESIASTES",
    "Lam": "LAMENTACIONES",
    "Miq": "MIQUEAS",
    "Ez": "EZEQUIEL",
    "Ex": "EXODO",
    "Dt": "DEUTERONOMIO",
    "Rut": "RUT",
    "Os": "OSEAS",
    "Sab": "SABIDURIA",
    "Eclo": "ECLESIASTICO",
    "Ef": "CARTA A LOS EFESIOS"
}

VERSICULOS = [
    ("Jn 3,16", "Dios amó tanto al mundo, que entregó a su Hijo único para que todo el que cree en él no muera, sino que tenga Vida eterna.", "mundo", ["pueblo", "hombre", "cielo"]),
    ("Jn 14,6", "Yo soy el Camino, la Verdad y la Vida. Nadie va al Padre, sino por mí.", "Verdad", ["Luz", "Paz", "Puerta"]),
    ("Jn 15,13", "No hay amor más grande que dar la vida por los amigos.", "amigos", ["hermanos", "pobres", "demás"]),
    ("Jn 15,16", "No son ustedes los que me eligieron a mí, sino yo el que los elegí a ustedes, y los destiné para que vayan y den fruto", "fruto", ["testimonio", "luz", "gracias"]),
    ("Jn 8,12", "Yo soy la luz del mundo. El que me sigue no andará en tinieblas, sino que tendrá la luz de la Vida", "tinieblas", ["soledad", "pecado", "vano"]),
    ("Jn 8,32", "conocerán la verdad y la verdad los hará libres", "libres", ["felices", "santos", "fuertes"]),
    ("Jn 6,35", "Yo soy el pan de Vida. El que viene a mí jamás tendrá hambre; el que cree en mí jamás tendrá sed.", "pan", ["agua", "camino", "vino"]),
    ("Jn 10,11", "Yo soy el buen Pastor. El buen Pastor da su vida por las ovejas.", "ovejas", ["amigos", "hermanos", "pobres"]),
    ("Jn 11,25", "Yo soy la Resurrección y la Vida. El que cree en mí, aunque muera, vivirá", "Resurrección", ["Luz", "Verdad", "Puerta"]),
    ("Jn 13,34", "Les doy un mandamiento nuevo: ámense los unos a los otros.", "nuevo", ["único", "eterno", "grande"]),
    ("Jn 1,14", "Y la Palabra se hizo carne y habitó entre nosotros.", "carne", ["luz", "hombre", "pan"]),
    ("Jn 10,10", "yo he venido para que las ovejas tengan Vida, y la tengan en abundancia.", "abundancia", ["plenitud", "paz", "libertad"]),
    ("Mt 5,3", "Felices los que tienen alma de pobres, porque a ellos les pertenece el Reino de los Cielos.", "pobres", ["niños", "santos", "justos"]),
    ("Mt 5,8", "Felices los que tienen el corazón puro, porque verán a Dios.", "puro", ["humilde", "abierto", "grande"]),
    ("Mt 5,9", "Felices los que trabajan por la paz, porque serán llamados hijos de Dios.", "paz", ["justicia", "verdad", "unidad"]),
    ("Mt 5,14", "Ustedes son la luz del mundo.", "luz", ["sal", "esperanza", "alegría"]),
    ("Mt 6,21", "Allí donde esté tu tesoro, estará también tu corazón.", "tesoro", ["familia", "fe", "casa"]),
    ("Mt 6,33", "Busquen primero el Reino y su justicia, y todo lo demás se les dará por añadidura.", "Reino", ["rostro", "camino", "amor"]),
    ("Mt 7,7", "Pidan y se les dará; busquen y encontrarán; llamen y se les abrirá.", "encontrarán", ["verán", "vivirán", "recibirán"]),
    ("Mt 11,28", "Vengan a mí todos los que están afligidos y agobiados, y yo los aliviaré.", "aliviaré", ["salvaré", "guiaré", "consolaré"]),
    ("Mt 18,20", "Porque donde hay dos o tres reunidos en mi Nombre, yo estoy presente en medio de ellos", "tres", ["cuatro", "diez", "doce"]),
    ("Mt 22,37", "Amarás al Señor, tu Dios, con todo tu corazón, con toda tu alma y con todo tu espíritu.", "alma", ["vida", "fuerza", "ser"]),
    ("Mt 28,20", "Y yo estaré siempre con ustedes hasta el fin del mundo", "siempre", ["hoy", "aquí", "también"]),
    ("Mt 16,18", "Tú eres Pedro, y sobre esta piedra edificaré mi iglesia", "piedra", ["roca", "tierra", "casa"]),
    ("Mt 25,40", "cada vez que lo hicieron con el más pequeño de mis hermanos, lo hicieron conmigo", "pequeño", ["pobre", "débil", "humilde"]),
    ("Mc 16,15", "Vayan por todo el mundo, anuncien la Buena Noticia a toda la creación.", "creación", ["gente", "tierra", "humanidad"]),
    ("Mc 10,27", "Para los hombres es imposible, pero no para Dios, porque para él todo es posible", "posible", ["fácil", "nuevo", "bueno"]),
    ("Lc 1,38", "Yo soy la servidora del Señor, que se cumpla en mí lo que has dicho", "servidora", ["hija", "elegida", "madre"]),
    ("Lc 1,37", "no hay nada imposible para Dios", "imposible", ["oculto", "pequeño", "lejano"]),
    ("Lc 6,36", "Sean misericordiosos, como el Padre de ustedes es misericordioso.", "misericordiosos", ["perfectos", "santos", "buenos"]),
    ("Lc 15,7", "habrá más alegría en el cielo por un solo pecador que se convierta, que por noventa y nueve justos", "noventa y nueve", ["cien", "mil", "setenta y siete"]),
    ("Lc 1,46-47", "Mi alma canta la grandeza del Señor, y mi espíritu se estremece de gozo en Dios, mi salvador", "grandeza", ["gloria", "bondad", "alegría"]),
    ("Hch 1,8", "recibirán la fuerza del Espíritu Santo que descenderá sobre ustedes, y serán mis testigos", "testigos", ["discípulos", "apóstoles", "amigos"]),
    ("Hch 20,35", "La felicidad está más en dar que en recibir", "dar", ["amar", "servir", "perdonar"]),
    ("Rom 8,31", "Si Dios está con nosotros, ¿quién estará contra nosotros?", "contra", ["sobre", "entre", "sin"]),
    ("Rom 12,21", "No te dejes vencer por el mal. Por el contrario, vence al mal, haciendo el bien.", "vencer", ["llevar", "asustar", "tentar"]),
    ("1 Cor 13,4", "El amor es paciente, es servicial; el amor no es envidioso", "paciente", ["fuerte", "eterno", "alegre"]),
    ("1 Cor 13,13", "ahora existen tres cosas: la fe, la esperanza y el amor", "esperanza", ["caridad", "paz", "alegría"]),
    ("2 Cor 12,9", "Te basta mi gracia, porque mi poder triunfa en la debilidad", "debilidad", ["humildad", "oración", "cruz"]),
    ("Gál 2,20", "ya no vivo yo, sino que Cristo vive en mí", "Cristo", ["Dios", "el Espíritu", "el amor"]),
    ("Gál 5,1", "Esta es la libertad que nos ha dado Cristo.", "libertad", ["paz", "vida", "gracia"]),
    ("Flp 4,13", "Yo lo puedo todo en aquel que me conforta.", "conforta", ["ama", "llama", "salva"]),
    ("Flp 4,4", "Alégrense siempre en el Señor. Vuelvo a insistir, alégrense.", "siempre", ["juntos", "hoy", "mucho"]),
    ("Col 3,14", "Sobre todo, revístanse del amor, que es el vínculo de la perfección.", "amor", ["humildad", "paciencia", "fe"]),
    ("1 Tes 5,17", "Oren sin cesar.", "cesar", ["miedo", "descanso", "excusas"]),
    ("1 Tim 4,12", "Que nadie menosprecie tu juventud", "juventud", ["fe", "palabra", "vocación"]),
    ("2 Tim 4,7", "he peleado hasta el fin el buen combate, concluí mi carrera, conservé la fe.", "combate", ["camino", "partido", "trabajo"]),
    ("Heb 13,8", "Jesucristo es el mismo ayer y hoy, y lo será para siempre.", "ayer", ["mañana", "aquí", "allá"]),
    ("Sant 2,17", "si no va acompañada de las obras, está completamente muerta.", "obras", ["oración", "alegría", "esperanza"]),
    ("1 Pe 5,7", "Descarguen en él todas sus inquietudes, ya que él se ocupa de ustedes.", "inquietudes", ["alegrías", "culpas", "tareas"]),
    ("1 Jn 4,8", "El que no ama no ha conocido a Dios, porque Dios es amor.", "amor", ["luz", "vida", "verdad"]),
    ("1 Jn 4,19", "Nosotros amamos porque Dios nos amó primero.", "primero", ["siempre", "tanto", "así"]),
    ("Ap 3,20", "Yo estoy junto a la puerta y llamo: si alguien oye mi voz y me abre, entraré en su casa y cenaremos juntos.", "puerta", ["ventana", "mesa", "entrada"]),
    ("Ap 21,5", "Yo hago nuevas todas las cosas", "nuevas", ["buenas", "santas", "eternas"]),
    ("Gn 1,27", "Dios creó al hombre a su imagen; lo creó a imagen de Dios, los creó varón y mujer.", "varón y mujer", ["libres y buenos", "padre y madre", "para amar"]),
    ("Gn 1,31", "Dios miró todo lo que había hecho, y vio que era muy bueno.", "bueno", ["grande", "bello", "nuevo"]),
    ("Sal 23,1", "El Señor es mi pastor, nada me puede faltar.", "pastor", ["guía", "refugio", "luz"]),
    ("Sal 27,1", "El Señor es mi luz y mi salvación, ¿a quién temeré?", "luz", ["roca", "fuerza", "pastor"]),
    ("Sal 119,105", "Tu palabra es una lámpara para mis pasos, y una luz en mi camino.", "lámpara", ["guía", "fuerza", "roca"]),
    ("Sal 139,14", "te doy gracias porque fui formado de manera tan admirable", "admirable", ["perfecta", "única", "especial"]),
    ("Sal 34,9", "¡Gusten y vean qué bueno es el Señor!", "Gusten", ["Canten", "Vengan", "Miren"]),
    ("Is 43,1", "No temas, porque yo te he redimido, te he llamado por tu nombre, tú me perteneces.", "nombre", ["lado", "voz", "camino"]),
    ("Is 41,10", "No temas, porque yo estoy contigo, no te inquietes, porque yo soy tu Dios", "contigo", ["cerca", "aquí", "delante"]),
    ("Is 49,15", "¿Se olvida una madre de su criatura, no se compadece del hijo de sus entrañas? ¡Pero aunque ella se olvide, yo no te olvidaré!", "madre", ["padre", "amiga", "hermana"]),
    ("Jer 29,11", "son planes de prosperidad y no de desgracia, para asegurarles un porvenir y una esperanza.", "esperanza", ["alegría", "promesa", "recompensa"]),
    ("Jer 1,5", "Antes de formarte en el vientre materno, yo te conocía", "conocía", ["amaba", "llamaba", "esperaba"]),
    ("Prov 3,5", "no te apoyes en tu propia inteligencia", "inteligencia", ["fuerza", "voluntad", "experiencia"]),
    ("Jos 1,9", "No temas ni te acobardes, porque el Señor, tu Dios, estará contigo dondequiera que vayas", "acobardes", ["aflijas", "detengas", "canses"]),
    ("1 Sam 3,10", "Habla, porque tu servidor escucha", "escucha", ["espera", "obedece", "responde"]),
    ("1 Sam 16,7", "el hombre ve las apariencias, pero Dios ve el corazón", "corazón", ["alma", "interior", "fondo"]),
    ("Ecl 3,1", "Hay un momento para todo y un tiempo para cada cosa bajo el sol", "tiempo", ["lugar", "motivo", "sentido"]),
    ("Lam 3,22-23", "La misericordia del Señor no se extingue ni se agota su compasión; ellas se renuevan cada mañana", "mañana", ["día", "noche", "momento"]),
    ("Miq 6,8", "practicar la justicia, amar la fidelidad y caminar humildemente con tu Dios.", "humildemente", ["alegremente", "firmemente", "siempre"]),
    ("Ez 36,26", "Les daré un corazón nuevo y pondré en ustedes un espíritu nuevo", "corazón", ["camino", "nombre", "hogar"]),
    ("Jn 4,14", "el que beba del agua que yo le daré, nunca más volverá a tener sed", "sed", ["hambre", "miedo", "dudas"]),
    ("Jn 6,68", "Señor, ¿a quién iremos? Tú tienes palabras de Vida eterna.", "palabras", ["promesas", "caminos", "gestos"]),
    ("Jn 12,24", "si el grano de trigo que cae en la tierra no muere, queda solo; pero si muere, da mucho fruto.", "trigo", ["mostaza", "arena", "uva"]),
    ("Jn 13,35", "En esto todos reconocerán que ustedes son mis discípulos: en el amor que se tengan los unos a los otros", "discípulos", ["amigos", "hermanos", "hijos"]),
    ("Jn 14,27", "Les dejo la paz, les doy mi paz, pero no como la da el mundo.", "mundo", ["tiempo", "hombre", "ley"]),
    ("Jn 15,5", "Yo soy la vid, ustedes los sarmientos", "vid", ["raíz", "luz", "semilla"]),
    ("Jn 15,9", "Como el Padre me amó, también yo los he amado a ustedes. Permanezcan en mi amor.", "Permanezcan", ["Confíen", "Crezcan", "Vivan"]),
    ("Jn 16,33", "En el mundo tendrán que sufrir; pero tengan valor: yo he vencido al mundo", "valor", ["paciencia", "fe", "calma"]),
    ("Jn 20,29", "¡Felices los que creen sin haber visto!", "visto", ["dudado", "escuchado", "tocado"]),
    ("Jn 2,5", "Hagan todo lo que él les diga", "Hagan", ["Escuchen", "Crean", "Recuerden"]),
    ("Jn 1,5", "La luz brilla en las tinieblas", "brilla", ["vence", "nace", "vive"]),
    ("Mt 5,44", "Amen a sus enemigos, rueguen por sus perseguidores", "enemigos", ["amigos", "vecinos", "hermanos"]),
    ("Mt 6,34", "No se inquieten por el día de mañana", "mañana", ["hoy", "ayer", "domingo"]),
    ("Mt 9,37", "La cosecha es abundante, pero los trabajadores son pocos.", "trabajadores", ["días", "frutos", "pastores"]),
    ("Mt 10,8", "Ustedes han recibido gratuitamente, den también gratuitamente.", "recibido", ["pedido", "ganado", "buscado"]),
    ("Mt 14,27", "Tranquilícense, soy yo; no teman.", "teman", ["duden", "corran", "lloren"]),
    ("Mt 4,19", "Síganme, y yo los haré pescadores de hombres", "pescadores", ["pastores", "sembradores", "constructores"]),
    ("Mt 16,24", "que renuncie a sí mismo, que cargue con su cruz y me siga", "cruz", ["carga", "vida", "mochila"]),
    ("Mc 9,23", "Todo es posible para el que cree", "cree", ["ama", "espera", "reza"]),
    ("Lc 1,28", "¡Alégrate!, llena de gracia, el Señor está contigo", "gracia", ["gloria", "luz", "fe"]),
    ("Lc 2,10", "No teman, porque les traigo una buena noticia, una gran alegría para todo el pueblo", "alegría", ["esperanza", "paz", "promesa"]),
    ("Lc 23,43", "Yo te aseguro que hoy estarás conmigo en el Paraíso", "Paraíso", ["cielo", "Reino", "camino"]),
    ("Lc 24,32", "¿No ardía acaso nuestro corazón, mientras nos hablaba en el camino", "ardía", ["latía", "temblaba", "saltaba"]),
    ("Lc 2,19", "María conservaba estas cosas y las meditaba en su corazón.", "meditaba", ["guardaba", "contaba", "escribía"]),
    ("Rom 5,8", "la prueba de que Dios nos ama es que Cristo murió por nosotros cuando todavía éramos pecadores.", "pecadores", ["niños", "débiles", "pequeños"]),
    ("Rom 12,12", "Alégrense en la esperanza, sean pacientes en la tribulación y perseverantes en la oración.", "perseverantes", ["constantes", "alegres", "humildes"]),
    ("Gál 6,9", "No nos cansemos de hacer el bien", "cansemos", ["olvidemos", "privemos", "avergoncemos"]),
    ("Flp 4,6", "No se angustien por nada", "angustien", ["preocupen", "quejen", "rindan"]),
    ("Col 3,23", "Cualquiera sea el trabajo de ustedes, háganlo de todo corazón", "corazón", ["esfuerzo", "alegría", "cuidado"]),
    ("Heb 11,1", "la fe es la garantía de los bienes que se esperan, la plena certeza de las realidades que no se ven.", "fe", ["esperanza", "gracia", "oración"]),
    ("Sant 1,22", "Pongan en práctica la Palabra y no se contenten sólo con oírla", "oírla", ["leerla", "aprenderla", "repetirla"]),
    ("Ap 22,20", "¡Ven, Señor Jesús!", "Ven", ["Quédate", "Vuelve", "Escucha"]),
    ("Gn 2,18", "No conviene que el hombre esté solo.", "solo", ["triste", "quieto", "lejos"]),
    ("Ex 20,12", "Honra a tu padre y a tu madre", "Honra", ["Escucha", "Ayuda", "Respeta"]),
    ("Sal 51,12", "Crea en mí, Dios mío, un corazón puro", "puro", ["nuevo", "grande", "fuerte"]),
    ("Sal 118,24", "Este es el día que hizo el Señor: alegrémonos y regocijémonos en él.", "día", ["tiempo", "momento", "año"]),
    ("Sal 121,2", "La ayuda me viene del Señor, que hizo el cielo y la tierra.", "ayuda", ["fuerza", "paz", "luz"]),
    ("Sal 136,1", "¡Den gracias al Señor, porque es bueno, porque es eterno su amor!", "eterno", ["grande", "fiel", "puro"]),
    ("Prov 17,17", "El amigo ama en cualquier ocasión", "amigo", ["padre", "hermano", "sabio"]),
    ("Is 40,31", "los que esperan en el Señor renuevan sus fuerzas, despliegan alas como las águilas", "águilas", ["palomas", "ángeles", "golondrinas"]),
    ("Is 6,8", "¡Aquí estoy: envíame!", "envíame", ["llévame", "úsame", "guíame"]),
    ("Jer 31,3", "Yo te amé con un amor eterno", "eterno", ["fiel", "grande", "infinito"]),
    ("Rut 1,16", "yo iré adonde tú vayas y viviré donde tú vivas", "iré", ["volveré", "estaré", "seguiré"]),
    ("Eclo 6,14", "Un amigo fiel no tiene precio", "precio", ["igual", "fin", "dueño"]),
    ("Sab 11,24", "Tú amas todo lo que existe", "amas", ["conoces", "cuidas", "ves"]),
    ("1 Cor 13,7", "todo lo espera", "espera", ["perdona", "olvida", "gana"]),
    ("1 Cor 16,14", "Todo lo que hagan, háganlo con amor.", "amor", ["alegría", "cuidado", "fe"]),
    ("2 Cor 5,17", "una nueva criatura", "criatura", ["persona", "vida", "historia"]),
    ("1 Tes 5,16", "Estén siempre alegres.", "alegres", ["atentos", "unidos", "dispuestos"]),
    ("1 Jn 3,18", "no amemos solamente con la lengua y de palabra, sino con obras y de verdad", "obras", ["gestos", "hechos", "fuerza"]),
    ("1 Jn 4,18", "En el amor no hay lugar para el temor", "temor", ["odio", "egoísmo", "mentira"]),
]
