"""Banco del juego «Santo del día» y del Diccionario de santos.

Cada santo tiene:
  nombre       Como aparece en el juego. Empezá con San/Santo/Santa/Beato/Beata/Venerable:
               las opciones incorrectas salen del mismo género (Santa/Beata = mujer).
  pistas       Cinco pistas en primera persona, de la más difícil a la más fácil.
  fiesta       "12 de octubre" (o vacío si no tiene). Aparece en el calendario.
  ficha        id de la historia completa en js/contenido.js (santos[]), o vacío.
  foto         Foto ya optimizada dentro de la web (img/...). Si está vacía, se genera desde foto_origen.
  foto_origen  Nombre del archivo original en la carpeta "fotos-santos" (al lado de la carpeta de la web).

Para sumar un santo: copiá un bloque al final, completalo y corré  python herramientas/armar_juegos.py
"""

SANTOS = [
    {"nombre": "San Carlo Acutis", "fiesta": "12 de octubre", "ficha": "carlo-acutis",
     "foto": "img/santos/carlo-acutis.jpg", "foto_origen": "",
     "pistas": [
        "Nací en Londres, pero crecí en Milán.",
        "Me encantaba programar y armar páginas web.",
        "Armé una exposición sobre los milagros eucarísticos del mundo.",
        "Decía que la Eucaristía era mi autopista al cielo.",
        "Morí de leucemia a los 15 años y me canonizaron en 2025."]},
    {"nombre": "San Pier Giorgio Frassati", "fiesta": "4 de julio", "ficha": "pier-giorgio-frassati",
     "foto": "img/santos/pier-giorgio-frassati.jpg", "foto_origen": "",
     "pistas": [
        "Nací en Turín en 1901, en una familia acomodada.",
        "Estudiaba ingeniería en minas.",
        "Ayudaba en secreto a los pobres con la Sociedad de San Vicente de Paúl.",
        "Me encantaba escalar montañas con mis amigos.",
        "Mi lema era «Verso l'alto»: ¡hacia lo alto!"]},
    {"nombre": "Santa Teresita del Niño Jesús", "fiesta": "1 de octubre", "ficha": "teresita",
     "foto": "img/santos/teresita.jpg", "foto_origen": "",
     "pistas": [
        "Entré al convento con solo 15 años.",
        "Nunca salí de mi convento en Francia, pero soy patrona de las misiones.",
        "Escribí Historia de un alma.",
        "Propuse un «caminito» de cosas pequeñas hechas con mucho amor.",
        "Me dicen la santa de las rosas y mi fiesta es el 1 de octubre."]},
    {"nombre": "San Maximiliano Kolbe", "fiesta": "14 de agosto", "ficha": "maximiliano-kolbe",
     "foto": "img/santos/maximiliano-kolbe.jpg", "foto_origen": "",
     "pistas": [
        "Fui sacerdote franciscano en Polonia.",
        "Fundé la Milicia de la Inmaculada.",
        "Usé la imprenta y la radio para anunciar el Evangelio.",
        "Los nazis me llevaron preso a un campo de concentración.",
        "Di mi vida en Auschwitz en lugar de un padre de familia."]},
    {"nombre": "San Agustín", "fiesta": "28 de agosto", "ficha": "agustin",
     "foto": "img/santos/agustin.jpg", "foto_origen": "",
     "pistas": [
        "Nací en el norte de África en el siglo IV.",
        "Pasé años buscando la verdad en filosofías y placeres.",
        "Mi madre rezó por mí durante muchos años.",
        "Escribí las Confesiones.",
        "Dije: «Nuestro corazón está inquieto hasta que descanse en ti»."]},
    {"nombre": "Santa Mónica", "fiesta": "27 de agosto", "ficha": "",
     "foto": "img/santos-juego/santa-monica.jpg", "foto_origen": "Santa-monica.jpg",
     "pistas": [
        "Viví en el norte de África en el siglo IV.",
        "Mi esposo tenía mal carácter y se convirtió al final de su vida.",
        "Recé durante muchos años por la conversión de mi hijo.",
        "Mi fiesta es el 27 de agosto, un día antes que la de mi hijo.",
        "Soy la madre de San Agustín."]},
    {"nombre": "San Francisco de Asís", "fiesta": "4 de octubre", "ficha": "",
     "foto": "img/santos-juego/san-francisco-de-asis.jpg", "foto_origen": "san-francisco-de-asis.jpg",
     "pistas": [
        "Era hijo de un rico comerciante de telas.",
        "Dejé todo, hasta mi ropa, para vivir en pobreza.",
        "Escuché: «Francisco, reconstruye mi Iglesia».",
        "Escribí el Cántico de las criaturas.",
        "Soy patrono de la ecología y de los animales."]},
    {"nombre": "Santa Clara de Asís", "fiesta": "11 de agosto", "ficha": "",
     "foto": "img/santos-juego/santa-clara-de-asis.jpg", "foto_origen": "santa-clara-de-asis.jpg",
     "pistas": [
        "Nací en Asís, en una familia noble.",
        "Me escapé de mi casa de noche para consagrarme a Dios.",
        "Fundé una orden de monjas que viven en pobreza.",
        "Fui gran amiga de San Francisco.",
        "Soy patrona de la televisión."]},
    {"nombre": "San José", "fiesta": "19 de marzo", "ficha": "",
     "foto": "img/santos-juego/san-jose.jpg", "foto_origen": "san-jose.jpg",
     "pistas": [
        "Era carpintero.",
        "Dios me habló en sueños varias veces.",
        "Llevé a mi familia a Egipto para protegerla.",
        "En la Biblia no aparece ninguna palabra mía.",
        "Soy el esposo de María y el padre adoptivo de Jesús."]},
    {"nombre": "San Juan Pablo II", "fiesta": "22 de octubre", "ficha": "juan-pablo-ii",
     "foto": "img/santos-juego/san-juan-pablo-ii.jpg", "foto_origen": "san-juan-pabloii.jpg",
     "pistas": [
        "Nací en Polonia en 1920.",
        "De joven fui actor de teatro y trabajé en una cantera.",
        "Fui Papa durante casi 27 años.",
        "Creé las Jornadas Mundiales de la Juventud.",
        "Mi nombre era Karol Wojtyła."]},
    {"nombre": "Santa Teresa de Calcuta", "fiesta": "5 de septiembre", "ficha": "teresa-de-calcuta",
     "foto": "img/santos-juego/santa-teresa-de-calcuta.jpg", "foto_origen": "santa-teresa-de-calcuta.jpg",
     "pistas": [
        "Nací en Skopie, en una familia albanesa.",
        "Fui profesora en un colegio de Calcuta.",
        "Fundé las Misioneras de la Caridad.",
        "Recibí el Premio Nobel de la Paz en 1979.",
        "Usaba un sari blanco con bordes azules."]},
    {"nombre": "San José Gabriel del Rosario Brochero", "fiesta": "16 de marzo", "ficha": "cura-brochero",
     "foto": "img/santos-juego/san-jose-gabriel-del-rosario-brochero.jpg", "foto_origen": "cura-brochero.jpg",
     "pistas": [
        "Nací en Córdoba en 1840.",
        "Recorría las sierras a lomo de mula.",
        "Construí caminos, acequias y una casa de ejercicios espirituales.",
        "Me enfermé de lepra por estar cerca de los enfermos.",
        "Me dicen el Cura Gaucho."]},
    {"nombre": "Santa María Antonia de Paz y Figueroa (Mama Antula)", "fiesta": "7 de marzo", "ficha": "",
     "foto": "img/santos-juego/santa-maria-antonia-de-paz-y-figueroa-ma.jpg", "foto_origen": "mama-antula.jpg",
     "pistas": [
        "Nací en Santiago del Estero.",
        "Caminé descalza miles de kilómetros.",
        "Organicé los ejercicios espirituales de San Ignacio cuando los jesuitas fueron expulsados.",
        "Fundé la Santa Casa de Ejercicios en Buenos Aires.",
        "Soy la primera santa argentina, canonizada en 2024."]},
    {"nombre": "Beato Ceferino Namuncurá", "fiesta": "26 de agosto", "ficha": "ceferino-namuncura",
     "foto": "img/santos-juego/beato-ceferino-namuncura.jpg", "foto_origen": "ceferino-namuncura.jpg",
     "pistas": [
        "Era hijo de un cacique mapuche.",
        "Estudié con los salesianos.",
        "Quería ser sacerdote para ayudar a mi pueblo.",
        "Morí de tuberculosis en Roma a los 18 años.",
        "Soy beato desde 2007."]},
    {"nombre": "Santa Josefina Bakhita", "fiesta": "8 de febrero", "ficha": "",
     "foto": "img/santos-juego/santa-josefina-bakhita.jpg", "foto_origen": "josefina-bakhita.jpg",
     "pistas": [
        "Nací en Sudán.",
        "Me secuestraron de chica y me vendieron como esclava.",
        "Mis captores me pusieron un nombre que significa «afortunada».",
        "En Italia conocí a Jesús y me hice religiosa canosiana.",
        "Soy patrona de Sudán y de las víctimas de la trata."]},
    {"nombre": "Santo Tomás Moro", "fiesta": "22 de junio", "ficha": "tomas-moro",
     "foto": "img/santos-juego/santo-tomas-moro.jpg", "foto_origen": "santo-tomas-moro.jpg",
     "pistas": [
        "Fui abogado y canciller de Inglaterra.",
        "Escribí Utopía.",
        "Me negué a aceptar al rey como jefe de la Iglesia.",
        "Me decapitaron en 1535.",
        "Soy patrono de los políticos y gobernantes."]},
    {"nombre": "Santa Teresa de Ávila", "fiesta": "15 de octubre", "ficha": "",
     "foto": "img/santos-juego/santa-teresa-de-avila.jpg", "foto_origen": "santa-teresa-de-avila.jpg",
     "pistas": [
        "Nací en España en 1515.",
        "Reformé la orden del Carmelo.",
        "Escribí Las Moradas.",
        "Dije: «Nada te turbe, nada te espante… solo Dios basta».",
        "Fui la primera mujer declarada Doctora de la Iglesia."]},
    {"nombre": "Santa Catalina de Siena", "fiesta": "29 de abril", "ficha": "catalina-de-siena",
     "foto": "img/santos-juego/santa-catalina-de-siena.jpg", "foto_origen": "santa-catalina-de-siena.jpg",
     "pistas": [
        "Viví en Italia en el siglo XIV.",
        "Fui laica dominica, sin entrar a un convento.",
        "Convencí al Papa de volver de Aviñón a Roma.",
        "Dicté el libro El Diálogo.",
        "Dije: «Si son lo que deben ser, prenderán fuego al mundo entero»."]},
    {"nombre": "San Juan Bosco", "fiesta": "31 de enero", "ficha": "juan-bosco",
     "foto": "img/santos-juego/san-juan-bosco.jpg", "foto_origen": "san-juan-bosco.jpg",
     "pistas": [
        "Nací en Italia en 1815.",
        "De chico hacía malabares para atraer a otros chicos y enseñarles a rezar.",
        "Fundé los salesianos.",
        "Me dedicaba a los jóvenes pobres de Turín.",
        "Soy patrono de los jóvenes y de los magos."]},
    {"nombre": "Santo Domingo Savio", "fiesta": "6 de mayo", "ficha": "",
     "foto": "img/santos-juego/santo-domingo-savio.jpg", "foto_origen": "santo-domingo-savio.jpg",
     "pistas": [
        "Fui alumno de Don Bosco.",
        "Mi lema era: «Antes morir que pecar».",
        "Fundé con mis amigos la Compañía de la Inmaculada.",
        "Morí a los 14 años.",
        "Soy patrono de los monaguillos."]},
    {"nombre": "San Ignacio de Loyola", "fiesta": "31 de julio", "ficha": "ignacio-de-loyola",
     "foto": "img/santos-juego/san-ignacio-de-loyola.jpg", "foto_origen": "san-ignacio-de-loyola.jpg",
     "pistas": [
        "Fui soldado y me hirieron en una batalla en Pamplona.",
        "Me convertí leyendo vidas de santos mientras me recuperaba.",
        "Escribí los Ejercicios Espirituales.",
        "Fundé la Compañía de Jesús.",
        "Mi lema: «A mayor gloria de Dios»."]},
    {"nombre": "San Francisco Javier", "fiesta": "3 de diciembre", "ficha": "francisco-javier",
     "foto": "img/santos-juego/san-francisco-javier.jpg", "foto_origen": "san-francisco-javier.jpg",
     "pistas": [
        "Fui compañero de estudios de San Ignacio en París.",
        "Fui uno de los primeros jesuitas.",
        "Misioné en la India y en Japón.",
        "Morí a las puertas de China.",
        "Soy patrono de las misiones."]},
    {"nombre": "Santa Rosa de Lima", "fiesta": "23 de agosto", "ficha": "",
     "foto": "img/santos-juego/santa-rosa-de-lima.jpg", "foto_origen": "santa-rosa-de-lima.jpg",
     "pistas": [
        "Nací en Lima en 1586.",
        "Fui terciaria dominica.",
        "Cuidaba enfermos y pobres en la casa de mi familia.",
        "Fui la primera santa de América.",
        "Soy patrona de América y del Perú."]},
    {"nombre": "San Martín de Porres", "fiesta": "3 de noviembre", "ficha": "martin-de-porres",
     "foto": "img/santos-juego/san-martin-de-porres.jpg", "foto_origen": "san-martin-de-porres.jpg",
     "pistas": [
        "Nací en Lima, hijo de un español y de una mujer liberta.",
        "Fui hermano dominico.",
        "Cuidaba enfermos y también a los animales.",
        "Me dicen el santo de la escoba.",
        "Soy patrono de la justicia social."]},
    {"nombre": "Santa Faustina Kowalska", "fiesta": "5 de octubre", "ficha": "faustina-kowalska",
     "foto": "img/santos-juego/santa-faustina-kowalska.jpg", "foto_origen": "santa-faustina.jpg",
     "pistas": [
        "Fui monja en Polonia.",
        "Escribí un diario con mensajes de Jesús.",
        "Jesús me pidió pintar una imagen con la frase «Jesús, en vos confío».",
        "Difundí la Coronilla de la Divina Misericordia.",
        "Juan Pablo II me canonizó en el año 2000."]},
    {"nombre": "San Pío de Pietrelcina (Padre Pío)", "fiesta": "23 de septiembre", "ficha": "padre-pio",
     "foto": "img/santos-juego/san-pio-de-pietrelcina-padre-pio.jpg", "foto_origen": "san-pio.jpg",
     "pistas": [
        "Fui fraile capuchino en Italia.",
        "Tuve los estigmas durante cincuenta años.",
        "Pasaba muchas horas por día confesando.",
        "Fundé un hospital: la Casa Alivio del Sufrimiento.",
        "Me dicen Padre Pío."]},
    {"nombre": "San Pedro", "fiesta": "29 de junio", "ficha": "",
     "foto": "img/santos-juego/san-pedro.jpg", "foto_origen": "san-pedro.jpg",
     "pistas": [
        "Era pescador en Galilea.",
        "Mi hermano se llamaba Andrés.",
        "Negué a Jesús tres veces.",
        "Jesús me cambió el nombre.",
        "Fui el primer Papa."]},
    {"nombre": "San Pablo", "fiesta": "29 de junio", "ficha": "san-pablo",
     "foto": "img/santos-juego/san-pablo.jpg", "foto_origen": "san-pablo.jpg",
     "pistas": [
        "Perseguía a los cristianos.",
        "Jesús se me apareció en el camino a Damasco.",
        "Quedé ciego durante tres días.",
        "Escribí muchas cartas del Nuevo Testamento.",
        "Antes me llamaba Saulo."]},
    {"nombre": "Santa María Magdalena", "fiesta": "22 de julio", "ficha": "",
     "foto": "img/santos-juego/santa-maria-magdalena.jpg", "foto_origen": "santa-maria-magdalena.jpg",
     "pistas": [
        "Jesús expulsó de mí siete demonios.",
        "Acompañé a Jesús hasta la cruz.",
        "Fui al sepulcro el domingo bien temprano.",
        "Fui la primera en ver a Jesús resucitado.",
        "Me llaman la apóstol de los apóstoles."]},
    {"nombre": "San Juan Evangelista", "fiesta": "27 de diciembre", "ficha": "",
     "foto": "img/santos-juego/san-juan-evangelista.jpg", "foto_origen": "san-juan-evangelista.jpg",
     "pistas": [
        "Era pescador, hijo de Zebedeo.",
        "Mi hermano era Santiago.",
        "Al pie de la cruz, Jesús me confió a su Madre.",
        "La tradición me atribuye un Evangelio y el Apocalipsis.",
        "Me llaman el discípulo amado."]},
    {"nombre": "Santa Juana de Arco", "fiesta": "30 de mayo", "ficha": "",
     "foto": "img/santos-juego/santa-juana-de-arco.jpg", "foto_origen": "santa-juana-de-arco.jpg",
     "pistas": [
        "Fui una campesina francesa.",
        "Escuchaba las voces de algunos santos.",
        "Lideré al ejército francés con 17 años.",
        "Me quemaron en la hoguera a los 19.",
        "Soy patrona de Francia."]},
    {"nombre": "San Óscar Romero", "fiesta": "24 de marzo", "ficha": "",
     "foto": "img/santos-juego/san-oscar-romero.jpg", "foto_origen": "san-oscar-romero.jpg",
     "pistas": [
        "Fui arzobispo de San Salvador.",
        "Defendí a los pobres en medio de la violencia.",
        "Me asesinaron mientras celebraba misa en 1980.",
        "El Papa Francisco me canonizó en 2018.",
        "Soy el primer santo de El Salvador."]},
    {"nombre": "Santa Gianna Beretta Molla", "fiesta": "28 de abril", "ficha": "",
     "foto": "img/santos-juego/santa-gianna-beretta-molla.jpg", "foto_origen": "santa-gianna.jpg",
     "pistas": [
        "Fui médica pediatra en Italia.",
        "Me casé y tuve cuatro hijos.",
        "En mi último embarazo elegí salvar la vida de mi hija.",
        "Morí en 1962.",
        "Soy patrona de las madres."]},
    {"nombre": "San Luis Gonzaga", "fiesta": "21 de junio", "ficha": "",
     "foto": "img/santos-juego/san-luis-gonzaga.jpg", "foto_origen": "san-luis-gonzaga.jpg",
     "pistas": [
        "Renuncié a ser marqués para hacerme jesuita.",
        "Cuidé enfermos de peste en Roma.",
        "Me contagié y morí a los 23 años.",
        "Mi fiesta es el 21 de junio.",
        "Soy patrono de la juventud."]},
    {"nombre": "San Benito", "fiesta": "11 de julio", "ficha": "san-benito",
     "foto": "img/santos-juego/san-benito.jpg", "foto_origen": "san-benito.jpg",
     "pistas": [
        "Viví como ermitaño en una cueva en Subiaco.",
        "Fundé el monasterio de Montecassino.",
        "Escribí una regla para los monjes.",
        "Mi lema es «Ora et labora».",
        "Soy patrono de Europa."]},
    {"nombre": "Santo Tomás de Aquino", "fiesta": "28 de enero", "ficha": "tomas-de-aquino",
     "foto": "img/santos-juego/santo-tomas-de-aquino.jpg", "foto_origen": "santo-tomas-aquino.jpg",
     "pistas": [
        "Mi familia me encerró para que no me hiciera dominico.",
        "Mis compañeros me decían «el buey mudo».",
        "Escribí la Suma Teológica.",
        "Compuse himnos a la Eucaristía, como el Pange lingua.",
        "Soy patrono de los estudiantes."]},
    {"nombre": "San John Henry Newman", "fiesta": "9 de octubre", "ficha": "john-henry-newman",
     "foto": "img/santos-juego/san-john-henry-newman.jpg", "foto_origen": "san-john-henry.jpg",
     "pistas": [
        "Fui pastor anglicano en Oxford.",
        "Me convertí al catolicismo en 1845.",
        "Fui nombrado cardenal.",
        "Escribí el poema «Guíame, luz amable».",
        "Me canonizaron en 2019."]},
    {"nombre": "San Juan Diego", "fiesta": "9 de diciembre", "ficha": "",
     "foto": "img/santos-juego/san-juan-diego.jpg", "foto_origen": "san-juan-diego.jpg",
     "pistas": [
        "Era un indígena de México.",
        "La Virgen se me apareció en el cerro del Tepeyac.",
        "Le llevé rosas al obispo envueltas en mi tilma.",
        "En mi tilma quedó estampada la imagen de la Virgen.",
        "Me canonizaron en 2002."]},
    {"nombre": "Santa Bernardita Soubirous", "fiesta": "16 de abril", "ficha": "",
     "foto": "img/santos-juego/santa-bernardita-soubirous.jpg", "foto_origen": "santa-bernardita.jpg",
     "pistas": [
        "Era una chica pobre de Francia.",
        "Vi a la Virgen dieciocho veces en una gruta.",
        "La Señora me dijo: «Yo soy la Inmaculada Concepción».",
        "Por su pedido brotó un manantial que todavía corre.",
        "Las apariciones fueron en Lourdes."]},
    {"nombre": "San José Sánchez del Río", "fiesta": "10 de febrero", "ficha": "",
     "foto": "img/santos-juego/san-jose-sanchez-del-rio.jpg", "foto_origen": "san-jose-sanchez.jpg",
     "pistas": [
        "Fui un adolescente mexicano.",
        "Me uní a los cristeros a los 14 años.",
        "Me torturaron para que renegara de mi fe.",
        "Morí gritando «¡Viva Cristo Rey!».",
        "Me canonizaron en 2016."]},
    {"nombre": "Santos Mártires de Canadá (Juan de Brébeuf, Isaac Jogues y compañeros)", "fiesta": "19 de octubre", "ficha": "martires-de-canada",
     "foto": "img/santos-juego/santos-martires-de-canada-juan-de-brebeu.jpg", "foto_origen": "santos-martires-de-canada.jpg",
     "pistas": [
        "Siglo XVII, en las tierras que hoy son Canadá y Estados Unidos.",
        "Misión entre el pueblo hurón, aprendiendo su lengua y sus costumbres.",
        "Una vida entregada a anunciar el Evangelio, hasta el martirio.",
        "Fiesta: 19 de octubre (en Canadá, el 26 de septiembre).",
        "Fuimos ocho misioneros, seis jesuitas y dos laicos: somos los patronos de Canadá."]},
    {"nombre": "San Antonio de Padua", "fiesta": "13 de junio", "ficha": "",
     "foto": "img/santos-juego/san-antonio-de-padua.jpg", "foto_origen": "san-antonio-de-padua.jpg",
     "pistas": [
        "Nací en Lisboa, Portugal.",
        "Primero fui canónigo agustino y después me hice franciscano.",
        "Fui un gran predicador: se cuenta que hasta los peces se acercaron a escucharme.",
        "Soy Doctor de la Iglesia.",
        "Me piden ayuda para encontrar cosas perdidas… y para conseguir novio."]},
    {"nombre": "San Felipe Neri", "fiesta": "26 de mayo", "ficha": "felipe-neri",
     "foto": "img/santos-juego/san-felipe-neri.jpg", "foto_origen": "san-felipe-neri.jpg",
     "pistas": [
        "Nací en Florencia en 1515.",
        "Fui sacerdote en Roma y fundé el Oratorio.",
        "Usaba el humor y las bromas para acercar a la gente a Dios.",
        "Les decía a los jóvenes: «Sean buenos, si pueden».",
        "Me dicen el santo de la alegría."]},
    {"nombre": "San Juan María Vianney (Santo Cura de Ars)", "fiesta": "4 de agosto", "ficha": "",
     "foto": "img/santos-juego/san-juan-maria-vianney-santo-cura-de-ars.jpg", "foto_origen": "san-juan-maria-vianney.jpg",
     "pistas": [
        "Me costaba muchísimo estudiar y casi no me ordenan sacerdote.",
        "Me mandaron a un pueblito de Francia de unos 230 habitantes.",
        "Pasaba muchísimas horas por día confesando.",
        "Gente de toda Francia viajaba para confesarse conmigo.",
        "Soy el patrono de los párrocos."]},
    {"nombre": "San Damián de Molokai", "fiesta": "10 de mayo", "ficha": "damian-de-molokai",
     "foto": "img/santos-juego/san-damian-de-molokai.jpg", "foto_origen": "san-damian-de-molokai.jpg",
     "pistas": [
        "Nací en Bélgica en 1840.",
        "Fui misionero en Hawái.",
        "Pedí ir a vivir con los enfermos de lepra aislados en una isla.",
        "Me contagié lepra y seguí sirviéndolos hasta morir.",
        "Me canonizaron en 2009."]},
    {"nombre": "San Charbel Makhlouf", "fiesta": "24 de julio", "ficha": "",
     "foto": "img/santos-juego/san-charbel-makhlouf.jpg", "foto_origen": "san-charbel.jpg",
     "pistas": [
        "Nací en el Líbano.",
        "Fui monje de la Iglesia maronita.",
        "Viví mis últimos 23 años como ermitaño.",
        "Después de mi muerte se atribuyeron muchísimos milagros a mi intercesión.",
        "Me canonizaron en 1977."]},
    {"nombre": "San Francisco de Sales", "fiesta": "24 de enero", "ficha": "francisco-de-sales",
     "foto": "img/santos-juego/san-francisco-de-sales.jpg", "foto_origen": "san-francisco-de-sales.jpg",
     "pistas": [
        "Nací en Saboya en 1567.",
        "Fui obispo de Ginebra.",
        "Escribí Introducción a la vida devota.",
        "Fundé con Santa Juana de Chantal la orden de la Visitación.",
        "Soy patrono de los periodistas y escritores."]},
    {"nombre": "Venerable Guido Schäffer", "fiesta": "", "ficha": "guido-schaffer",
     "foto": "img/santos-juego/venerable-guido-schaffer.jpg", "foto_origen": "guido-schaffer.jpg",
     "pistas": [
        "Nací en Brasil en 1974.",
        "Fui médico y atendía gratis a los pobres.",
        "Me encantaba surfear.",
        "Estaba en el seminario para ser sacerdote.",
        "Morí en 2009 en el mar, mientras surfeaba. Me dicen el «ángel surfista»."]},
    {"nombre": "Enrique Shaw", "fiesta": "", "ficha": "enrique-shaw",
     "foto": "img/santos-juego/enrique-shaw.jpg", "foto_origen": "enrique-shaw.jpg",
     "pistas": [
        "Nací en París en 1921, en una familia argentina.",
        "Fui oficial de la Marina argentina.",
        "Dejé la Marina para ser empresario y vivir la fe en el trabajo.",
        "Fundé la Asociación Cristiana de Dirigentes de Empresa (ACDE).",
        "Cuando me enfermé de cáncer, cientos de empleados de mi empresa donaron sangre para mí."]},
    {"nombre": "Santa Inés", "fiesta": "21 de enero", "ficha": "",
     "foto": "img/santos-juego/santa-ines.jpg", "foto_origen": "Santa-ines.jpg",
     "pistas": [
        "Viví en Roma a comienzos del siglo IV.",
        "Era muy joven: tenía unos doce o trece años.",
        "Rechacé casarme porque me había consagrado a Cristo.",
        "Morí mártir por no renunciar a mi fe.",
        "Me representan con un cordero: en latín, cordero se dice agnus."]},
    {"nombre": "Santa Cecilia", "fiesta": "22 de noviembre", "ficha": "",
     "foto": "img/santos-juego/santa-cecilia.jpg", "foto_origen": "santa-cecilia.jpg",
     "pistas": [
        "Viví en Roma en los primeros siglos del cristianismo.",
        "Fui una joven noble que se consagró a Dios.",
        "Según la tradición, ayudé a convertir a mi esposo, Valeriano.",
        "Morí mártir.",
        "Soy la patrona de la música y de los músicos."]},
    {"nombre": "Santa Rita de Casia", "fiesta": "22 de mayo", "ficha": "",
     "foto": "img/santos-juego/santa-rita-de-casia.jpg", "foto_origen": "santa-rita.jpg",
     "pistas": [
        "Nací en Italia en el siglo XIV.",
        "Estuve casada con un hombre violento y perdoné a quienes lo mataron.",
        "Al quedar viuda entré en un convento agustino.",
        "Tenía en la frente una herida como la de una espina.",
        "Soy la santa de las causas imposibles."]},
    {"nombre": "Santa Ana", "fiesta": "26 de julio", "ficha": "",
     "foto": "img/santos-juego/santa-ana.jpg", "foto_origen": "santa-ana.jpg",
     "pistas": [
        "No aparezco en la Biblia: me conocemos por la tradición.",
        "Mi esposo se llamaba Joaquín.",
        "Mi fiesta es el 26 de julio.",
        "Soy la patrona de las abuelas.",
        "Soy la madre de la Virgen María."]},
    {"nombre": "Santa Jacinta Marto", "fiesta": "20 de febrero", "ficha": "",
     "foto": "img/santos-juego/santa-jacinta-marto.jpg", "foto_origen": "santa-jacinta-marto.jpg",
     "pistas": [
        "Nací en Portugal en 1910.",
        "Era la más chica de tres primos que cuidaban ovejas.",
        "Mi hermano Francisco también es santo.",
        "Morí en 1920, con solo 9 años.",
        "La Virgen se nos apareció en Fátima."]},
    {"nombre": "Santa Escolástica", "fiesta": "10 de febrero", "ficha": "",
     "foto": "img/santos-juego/santa-escolastica.jpg", "foto_origen": "santa-ecolastica.jpg",
     "pistas": [
        "Viví en Italia en el siglo VI.",
        "Fundé un monasterio de monjas cerca de Montecassino.",
        "Según la tradición, mi hermano y yo éramos mellizos.",
        "Recé y se desató una tormenta para que mi hermano se quedara a conversar conmigo.",
        "Soy la hermana de San Benito."]},
    {"nombre": "Santa Águeda", "fiesta": "5 de febrero", "ficha": "",
     "foto": "img/santos-juego/santa-agueda.jpg", "foto_origen": "santa-agueda.jpg",
     "pistas": [
        "Viví en Sicilia en el siglo III.",
        "Me consagré a Dios y rechacé a un gobernador romano.",
        "Me torturaron cruelmente por mi fe.",
        "Morí mártir en Catania.",
        "Soy patrona de las enfermeras y de las mujeres con cáncer de mama."]},
    {"nombre": "Santa Catalina Labouré", "fiesta": "28 de noviembre", "ficha": "",
     "foto": "img/santos-juego/santa-catalina-laboure.jpg", "foto_origen": "santa-catalina-laboure.jpg",
     "pistas": [
        "Nací en Francia en 1806.",
        "Fui Hija de la Caridad, la congregación de San Vicente de Paúl.",
        "La Virgen se me apareció en una capilla de París en 1830.",
        "Me pidió que hiciera acuñar una medalla.",
        "Gracias a mí se difundió la Medalla Milagrosa."]},
    {"nombre": "San Esteban", "fiesta": "26 de diciembre", "ficha": "",
     "foto": "img/santos-juego/san-esteban.jpg", "foto_origen": "san-esteban.jpg",
     "pistas": [
        "Fui uno de los siete diáconos elegidos por los apóstoles.",
        "Los Hechos dicen que estaba lleno de gracia y de poder.",
        "Me apedrearon en Jerusalén, y Saulo estaba presente.",
        "Antes de morir perdoné a los que me mataban.",
        "Soy el primer mártir cristiano."]},
    {"nombre": "San Alberto Hurtado", "fiesta": "18 de agosto", "ficha": "alberto-hurtado",
     "foto": "img/santos-juego/san-alberto-hurtado.jpg", "foto_origen": "san-alberto-hurtado.jpg",
     "pistas": [
        "Nací en Chile en 1901.",
        "Fui sacerdote jesuita.",
        "Recorría Santiago en una camioneta verde buscando a los que vivían en la calle.",
        "Fundé el Hogar de Cristo.",
        "Mi frase era: «Contento, Señor, contento»."]},
    {"nombre": "San Juan de la Cruz", "fiesta": "14 de diciembre", "ficha": "",
     "foto": "img/santos-juego/san-juan-de-la-cruz.jpg", "foto_origen": "san-juan-de-la-cruz.jpg",
     "pistas": [
        "Nací en España en 1542.",
        "Fui fraile carmelita.",
        "Ayudé a Santa Teresa de Ávila a reformar el Carmelo.",
        "Mis propios hermanos de orden me encerraron en una celda.",
        "Escribí el poema «Noche oscura»."]},
    {"nombre": "San Vicente de Paúl", "fiesta": "27 de septiembre", "ficha": "",
     "foto": "img/santos-juego/san-vicente-de-paul.jpg", "foto_origen": "san-vicente-de-paul.jpg",
     "pistas": [
        "Nací en Francia en 1581.",
        "Fundé la Congregación de la Misión.",
        "Con Santa Luisa de Marillac fundé las Hijas de la Caridad.",
        "Una sociedad que lleva mi nombre ayuda hoy a los pobres en todo el mundo.",
        "Soy el patrono de todas las obras de caridad."]},
    {"nombre": "San Ramón Nonato", "fiesta": "31 de agosto", "ficha": "",
     "foto": "img/santos-juego/san-ramon-nonato.jpg", "foto_origen": "san-ramon-nonato.jpg",
     "pistas": [
        "Nací en Cataluña en el siglo XIII.",
        "Me llaman «no nacido» porque me sacaron del vientre de mi madre ya muerta.",
        "Fui fraile mercedario.",
        "Me entregué como rehén para liberar a cristianos cautivos.",
        "Soy el patrono de las embarazadas y de los partos."]},
    {"nombre": "San Dimas", "fiesta": "25 de marzo", "ficha": "",
     "foto": "img/santos-juego/san-dimas.jpg", "foto_origen": "san-dimas.jpg",
     "pistas": [
        "Viví en tiempos de Jesús.",
        "Fui ladrón.",
        "Me crucificaron al lado de Jesús.",
        "Le pedí a Jesús que se acordara de mí cuando llegara a su Reino.",
        "Jesús me prometió: «Hoy estarás conmigo en el Paraíso»."]},
    {"nombre": "San Cristóbal", "fiesta": "25 de julio", "ficha": "",
     "foto": "img/santos-juego/san-cristobal.jpg", "foto_origen": "san-cristobal.jpg",
     "pistas": [
        "Según la tradición, era un hombre gigante.",
        "Ayudaba a la gente a cruzar un río llevándola sobre los hombros.",
        "Un día cargué a un niño que pesaba como el mundo entero.",
        "Mi nombre significa «el que lleva a Cristo».",
        "Soy el patrono de los viajeros y los conductores."]},
    {"nombre": "San Camilo de Lelis", "fiesta": "14 de julio", "ficha": "",
     "foto": "img/santos-juego/san-camilo-de-lelis.jpg", "foto_origen": "san-camilo-lelis.jpg",
     "pistas": [
        "Nací en Italia en 1550.",
        "De joven fui soldado y jugador.",
        "Una herida en la pierna me llevó a un hospital, donde descubrí mi vocación.",
        "Fundé una orden que lleva una cruz roja en el hábito.",
        "Soy el patrono de los enfermos, los hospitales y los enfermeros."]},
    {"nombre": "Santiago Apóstol", "fiesta": "25 de julio", "ficha": "santiago-apostol",
     "foto": "img/santos-juego/santiago-apostol.jpg", "foto_origen": "santiago-apostol.jpg",
     "pistas": [
        "Era pescador en Galilea.",
        "Mi padre se llamaba Zebedeo.",
        "Jesús nos llamó a mi hermano y a mí «hijos del trueno».",
        "Fui el primer apóstol en morir mártir.",
        "Muchos peregrinan a mi tumba por el Camino de Santiago."]},
    {"nombre": "San Bernardo de Claraval", "fiesta": "20 de agosto", "ficha": "",
     "foto": "img/santos-juego/san-bernardo-de-claraval.jpg", "foto_origen": "san-bernardo-de-claraval.jpg",
     "pistas": [
        "Nací en Francia en 1090.",
        "Entré al Císter con unos treinta compañeros, varios de ellos hermanos míos.",
        "Fundé la abadía de Claraval.",
        "Fui un gran predicador y amaba mucho a la Virgen.",
        "Me llaman el «Doctor Melifluo», de palabras dulces como la miel."]},
]
