"""Cursos de Academia Frassati (página academia.html).

Cada curso: lectura + examen. El examen toma 10 preguntas al azar del banco y se aprueba con 8.
Cada pregunta: p (pregunta), ok (respuesta correcta), otras (3 incorrectas), ref (dónde está en la lectura).
Las respuestas salen textualmente de la fuente citada en "ref". Si cambiás algo, revisá la fuente.

Después de editar:  python herramientas/armar_formacion.py
"""

COMPENDIO = 'https://www.vatican.va/archive/compendium_ccc/documents/archive_2005_compendium-ccc_sp.html'
OGMR = 'https://www.vatican.va/roman_curia/congregations/ccdds/documents/rc_con_ccdds_doc_20030317_ordinamento-messale_sp.html'
CV = 'https://www.vatican.va/content/francesco/es/apost_exhortations/documents/papa-francesco_esortazione-ap_20190325_christus-vivit.html'

CURSOS = [
    dict(
        id='sacramentos', icono='🕯️', titulo='Los sacramentos',
        resumen='Qué es cada sacramento, cómo se celebra, quién lo da y qué efectos tiene.',
        para='Ideal para Confirmación y para cualquiera que quiera entender mejor su fe.',
        minutos=40,
        lecturas=[dict(texto='Cuadernillo de la cumbre (PDF)', url='docs/academia/cumbre-01-sacramentos.pdf',
                       guia='El texto del Compendio con una guía de lectura, frases destacadas y preguntas para detenerse. Para leer en el celular o imprimir.'),
                  dict(texto='Compendio del Catecismo, preguntas 224 a 350', url=COMPENDIO,
                       guia='Buscá la Segunda Parte, «Los siete sacramentos de la Iglesia». Son preguntas cortas con su respuesta.')],
        preguntas=[
            dict(p='¿Cuántos sacramentos hay?', ok='Siete', otras=['Cinco', 'Tres', 'Doce'], ref='Compendio 224'),
            dict(p='¿Cuáles son los sacramentos de la iniciación cristiana?', ok='Bautismo, Confirmación y Eucaristía',
                 otras=['Bautismo, Penitencia y Eucaristía', 'Bautismo, Confirmación y Matrimonio', 'Confirmación, Eucaristía y Orden'], ref='Compendio 250'),
            dict(p='¿Cuáles son los sacramentos de curación?', ok='Penitencia y Unción de los enfermos',
                 otras=['Bautismo y Penitencia', 'Unción de los enfermos y Orden', 'Eucaristía y Matrimonio'], ref='Compendio 250'),
            dict(p='¿Qué sacramentos imprimen «carácter» y por eso se reciben una sola vez en la vida?', ok='Bautismo, Confirmación y Orden',
                 otras=['Bautismo, Eucaristía y Matrimonio', 'Confirmación, Orden y Matrimonio', 'Bautismo, Confirmación y Eucaristía'], ref='Compendio 227'),
            dict(p='¿En qué consiste el rito esencial del Bautismo?', ok='Sumergir en el agua o derramar agua sobre la cabeza invocando al Padre, al Hijo y al Espíritu Santo',
                 otras=['Ungir la frente con el santo crisma', 'Imponer las manos sobre la cabeza', 'Encender una vela en el cirio pascual'], ref='Compendio 256'),
            dict(p='En caso de necesidad, ¿quién puede bautizar?', ok='Cualquier persona que tenga la intención de hacer lo que hace la Iglesia',
                 otras=['Solo un obispo', 'Solo un sacerdote o un diácono', 'Solo un catequista con permiso del párroco'], ref='Compendio 260'),
            dict(p='En la Confirmación (rito latino), ¿qué palabras acompañan la unción con el crisma?', ok='«Recibe por esta señal el don del Espíritu Santo»',
                 otras=['«Yo te bautizo en el nombre del Padre…»', '«Yo te absuelvo de tus pecados»', '«El Cuerpo de Cristo»'], ref='Compendio 267'),
            dict(p='¿Quién es el ministro originario de la Confirmación?', ok='El obispo', otras=['El párroco', 'El padrino', 'El diácono'], ref='Compendio 270'),
            dict(p='¿Cuáles son los elementos esenciales para celebrar la Eucaristía?', ok='Pan de trigo y vino de vid',
                 otras=['Pan de cualquier cereal y jugo de uva', 'Pan sin levadura y agua', 'Hostia y vino de cualquier fruta'], ref='Compendio 279'),
            dict(p='¿Qué significa «transubstanciación»?', ok='La conversión de toda la sustancia del pan y del vino en la sustancia del Cuerpo y la Sangre de Cristo',
                 otras=['Que Cristo está en el pan solo de manera simbólica', 'Que el pan consagrado cambia de color y de sabor', 'La bendición de los alimentos antes de comer'], ref='Compendio 283'),
            dict(p='¿Cuándo instituyó Jesús la Eucaristía?', ok='El Jueves Santo, en la Última Cena',
                 otras=['En las bodas de Caná', 'En la multiplicación de los panes', 'El domingo de Pascua, en Emaús'], ref='Compendio 272'),
            dict(p='¿Cuáles son los actos propios del penitente en la Reconciliación?', ok='Examen de conciencia, contrición, confesión y satisfacción',
                 otras=['Ayuno, oración y limosna', 'Confesión y comunión', 'Contrición y renovación de las promesas del Bautismo'], ref='Compendio 303'),
            dict(p='¿Cada cuánto, como mínimo, hay que confesar los pecados graves?', ok='Al menos una vez al año',
                 otras=['Una vez en la vida', 'Todas las semanas', 'Solo antes de casarse'], ref='Compendio 305'),
            dict(p='¿Qué es el sigilo sacramental?', ok='El secreto absoluto, sin ninguna excepción, sobre los pecados conocidos en la confesión',
                 otras=['Puede contarse si es por el bien del penitente', 'El confesor debe informar al obispo', 'Puede contarse después de muchos años'], ref='Compendio 309'),
            dict(p='¿Quién puede recibir la Unción de los enfermos?', ok='Cualquier fiel que comienza a estar en peligro de muerte por enfermedad o vejez',
                 otras=['Solo quien está a punto de morir', 'Solo los sacerdotes ancianos', 'Cualquier persona, una sola vez en la vida'], ref='Compendio 316'),
            dict(p='¿Qué es el Viático?', ok='La Eucaristía que reciben quienes están por dejar esta vida',
                 otras=['Otro nombre de la Unción de los enfermos', 'Una bendición para los viajes', 'La primera comunión de un adulto'], ref='Compendio 320'),
            dict(p='¿Cuáles son los tres grados del sacramento del Orden?', ok='Episcopado, presbiterado y diaconado',
                 otras=['Papa, obispo y sacerdote', 'Seminarista, diácono y sacerdote', 'Cardenal, obispo y párroco'], ref='Compendio 325'),
            dict(p='¿Para qué fines instituyó Dios el Matrimonio?', ok='El bien de los cónyuges y la procreación y educación de los hijos',
                 otras=['Solo para tener hijos', 'Para que la pareja tenga los mismos bienes', 'Para que los esposos puedan ser padrinos'], ref='Compendio 338'),
            dict(p='¿Qué hace el Matrimonio, según el Compendio?', ok='El consentimiento: la voluntad del hombre y la mujer de entregarse mutua y definitivamente',
                 otras=['La firma del acta en el registro civil', 'La bendición de los anillos', 'La fiesta con la familia'], ref='Compendio 344'),
            dict(p='¿Qué obligación pone la Iglesia sobre la sagrada Comunión?', ok='Recibirla, con las debidas disposiciones, al menos en Pascua',
                 otras=['Recibirla todos los días', 'Recibirla solo en Navidad', 'No hay ninguna obligación'], ref='Compendio 290'),
        ]),
    dict(
        id='misa', icono='⛪', titulo='La misa, parte por parte',
        resumen='Qué pasa y por qué en cada momento de la misa, de la entrada a la despedida.',
        para='Para vivir la misa sabiendo lo que pasa en cada momento.',
        minutos=35,
        lecturas=[dict(texto='Cuadernillo de la cumbre (PDF)', url='docs/academia/cumbre-02-misa.pdf',
                       guia='La Instrucción General del Misal Romano con una guía de lectura, frases destacadas y preguntas para detenerse. Para leer en el celular o imprimir.'),
                  dict(texto='Instrucción General del Misal Romano, números 27 a 90', url=OGMR,
                       guia='Buscá el capítulo II, «Estructura de la Misa, sus elementos y sus partes». Los números 46 a 90 recorren la misa en orden.'),
                  dict(texto='Compendio del Catecismo, pregunta 277', url=COMPENDIO,
                       guia='Un resumen de cómo se desarrolla la celebración, en un solo párrafo.')],
        preguntas=[
            dict(p='¿Cuáles son las dos grandes partes de la misa?', ok='La Liturgia de la Palabra y la Liturgia Eucarística',
                 otras=['La entrada y la despedida', 'El Gloria y el Credo', 'La homilía y la comunión'], ref='IGMR 28'),
            dict(p='¿Qué forma parte de los ritos iniciales?', ok='La entrada, el saludo, el acto penitencial, el Señor ten piedad, el Gloria y la colecta',
                 otras=['Las lecturas, el salmo y la homilía', 'El Padrenuestro, la paz y la comunión', 'Los avisos, la bendición y la despedida'], ref='IGMR 46'),
            dict(p='La absolución con la que termina el acto penitencial…', ok='No tiene la eficacia del sacramento de la Penitencia',
                 otras=['Perdona también los pecados graves', 'Reemplaza a la confesión', 'Solo la puede dar el obispo'], ref='IGMR 51'),
            dict(p='¿En qué tiempos litúrgicos no se dice el Gloria los domingos?', ok='En Adviento y en Cuaresma',
                 otras=['En Navidad y en Pascua', 'En el Tiempo Ordinario', 'Nunca se omite'], ref='IGMR 53'),
            dict(p='¿Cómo se llama la oración con la que el sacerdote cierra los ritos iniciales?', ok='La colecta',
                 otras=['El prefacio', 'El embolismo', 'La doxología'], ref='IGMR 54'),
            dict(p='¿Desde dónde se proclaman las lecturas en la misa con el pueblo?', ok='Desde el ambón',
                 otras=['Desde el altar', 'Desde la sede', 'Desde el sagrario'], ref='IGMR 58'),
            dict(p='¿Cuál es la cumbre de la Liturgia de la Palabra?', ok='La lectura del Evangelio',
                 otras=['El salmo responsorial', 'La homilía', 'La oración universal'], ref='IGMR 60'),
            dict(p='En Cuaresma, ¿qué se canta en lugar del Aleluya?', ok='El versículo antes del Evangelio que trae el leccionario',
                 otras=['El Gloria', 'El Santo', 'Nada: se lee directamente el Evangelio'], ref='IGMR 62'),
            dict(p='¿Quién puede hacer la homilía?', ok='El sacerdote o, a veces, un diácono; nunca un laico',
                 otras=['Cualquier catequista preparado', 'Solo el obispo', 'Un laico, si el sacerdote lo autoriza'], ref='IGMR 66'),
            dict(p='¿Cuándo se reza el Credo (profesión de fe)?', ok='Los domingos y en las solemnidades',
                 otras=['Todos los días', 'Solo en Navidad y Pascua', 'Solo cuando hay bautismos'], ref='IGMR 68'),
            dict(p='En la oración universal (oración de los fieles), el pueblo…', ok='Ejerce su sacerdocio bautismal ofreciendo súplicas por la salvación de todos',
                 otras=['Escucha en silencio sin responder', 'Pide perdón por sus pecados', 'Renueva las promesas del Bautismo'], ref='IGMR 69'),
            dict(p='¿Qué expresa el lavatorio de manos del sacerdote en la preparación de los dones?', ok='El deseo de purificación interior',
                 otras=['Una medida de higiene antes de tocar el pan', 'El lavatorio de los pies de Jesús', 'El final de la Liturgia de la Palabra'], ref='IGMR 76'),
            dict(p='¿Qué es el «centro y la cumbre» de toda la celebración?', ok='La Plegaria Eucarística',
                 otras=['La homilía', 'El canto de entrada', 'La bendición final'], ref='IGMR 78'),
            dict(p='Dentro de la Plegaria Eucarística, ¿qué es la epíclesis?', ok='La invocación del Espíritu Santo para que los dones se conviertan en el Cuerpo y la Sangre de Cristo',
                 otras=['El canto del Santo', 'El saludo de la paz', 'La oración por los difuntos'], ref='IGMR 79'),
            dict(p='El «Santo» es…', ok='Una aclamación que forma parte de la Plegaria Eucarística',
                 otras=['El canto de entrada', 'Parte de los ritos de conclusión', 'Una lectura del Antiguo Testamento'], ref='IGMR 79'),
            dict(p='En el Padrenuestro de la misa, el «pan de cada día» indica para los cristianos principalmente…', ok='El pan eucarístico',
                 otras=['La comida de la familia', 'El trabajo de cada día', 'La Palabra de Dios'], ref='IGMR 81'),
            dict(p='¿Qué significa el gesto de la fracción del pan?', ok='Que, siendo muchos, formamos un solo cuerpo al comulgar del único Pan de vida',
                 otras=['Que el pan alcance para todos', 'Que Cristo se divide en partes', 'Que termina la Plegaria Eucarística'], ref='IGMR 83'),
            dict(p='¿Qué canto acompaña la fracción del pan?', ok='El Cordero de Dios', otras=['El Gloria', 'El Aleluya', 'El Santo'], ref='IGMR 83'),
            dict(p='¿Cómo escuchan los fieles la proclamación del Evangelio?', ok='De pie', otras=['Sentados', 'De rodillas', 'Como cada uno prefiera'], ref='IGMR 43 y 60'),
            dict(p='¿Qué forma parte del rito de conclusión?', ok='Los avisos, el saludo y la bendición, la despedida y el beso del altar',
                 otras=['La colecta y el Gloria', 'El Credo y la oración universal', 'La paz y la comunión'], ref='IGMR 90'),
        ]),
    dict(
        id='coordinador', icono='🧭', titulo='¿Cómo ser un buen coordinador?',
        resumen='Lo que el Papa Francisco pide a quienes acompañan a otros jóvenes: escuchar, acompañar procesos y anunciar a Jesús.',
        para='Para coordinadores y para quienes se están preparando para serlo.',
        minutos=45,
        lecturas=[dict(texto='Cuadernillo de la cumbre (PDF)', url='docs/academia/cumbre-03-coordinador.pdf',
                       guia='Christus vivit con una guía de lectura, frases destacadas y preguntas para detenerse. Para leer en el celular o imprimir.'),
                  dict(texto='Christus vivit, capítulo 7 (números 202 a 247)', url=CV,
                       guia='«La pastoral de los jóvenes»: las dos líneas de acción, los ambientes, la pastoral popular y el acompañamiento de los adultos.'),
                  dict(texto='Christus vivit, números 291 a 298', url=CV,
                       guia='Al final del capítulo 9: cómo escuchar y acompañar a otro en su discernimiento.')],
        preguntas=[
            dict(p='¿Cuáles son las dos grandes líneas de acción de la pastoral juvenil?', ok='La búsqueda (convocar) y el crecimiento (acompañar la maduración)',
                 otras=['La oración y el estudio', 'La liturgia y la caridad', 'La disciplina y la obediencia'], ref='CV 209'),
            dict(p='¿Quiénes son agentes de la pastoral juvenil?', ok='Los mismos jóvenes, acompañados y guiados',
                 otras=['Solo los sacerdotes', 'Solo los adultos de la parroquia', 'Los padres de los jóvenes'], ref='CV 203'),
            dict(p='¿Con qué lenguaje hay que acercarse a los jóvenes?', ok='Con la gramática del amor, no con el proselitismo',
                 otras=['Con argumentos para ganar cualquier debate', 'Con reglas claras desde el primer día', 'Con todos los contenidos doctrinales completos'], ref='CV 211'),
            dict(p='¿Qué advierte el Papa sobre la formación después de un encuentro fuerte con Jesús?', ok='Que si solo se ofrecen encuentros doctrinales y morales, muchos se aburren y pierden el fuego',
                 otras=['Que hay que dar todos los temas morales lo antes posible', 'Que no hace falta ninguna formación', 'Que conviene esperar años antes de formar'], ref='CV 212'),
            dict(p='¿Cuáles son los dos grandes ejes de todo camino formativo?', ok='Profundizar el kerygma y crecer en el amor fraterno',
                 otras=['Estudiar la Biblia y el Catecismo', 'Ir a misa y confesarse', 'Organizar eventos y recaudar fondos'], ref='CV 213'),
            dict(p='¿Qué es el kerygma?', ok='La experiencia fundante del encuentro con Dios a través de Cristo muerto y resucitado',
                 otras=['Un documento del Papa', 'Una forma de oración en grupo', 'Las reglas de la vida comunitaria'], ref='CV 213'),
            dict(p='Según Christus vivit, la pastoral juvenil solo puede ser…', ok='Sinodal: un «caminar juntos» que valora los carismas de cada uno',
                 otras=['Dirigida exclusivamente por el párroco', 'Igual en todas las parroquias del mundo', 'Para un grupo selecto de jóvenes'], ref='CV 206'),
            dict(p='¿Por qué hace falta una acogida cordial en nuestras comunidades?', ok='Porque muchos jóvenes llegan en una profunda situación de orfandad',
                 otras=['Porque así vienen más a misa', 'Porque lo exige el reglamento', 'Porque los jóvenes no tienen amigos'], ref='CV 216'),
            dict(p='¿Qué dice Christus vivit sobre el servicio a los demás?', ok='Que a menudo es el primer paso para descubrir o redescubrir la vida cristiana',
                 otras=['Que es solo para los que ya tienen mucha fe', 'Que distrae de la formación', 'Que debe hacerse solo en vacaciones'], ref='CV 225'),
            dict(p='¿Cómo son los líderes «populares» que pide el Papa?', ok='Los que incorporan a todos, también a los más pobres, débiles y heridos',
                 otras=['Los que tienen más seguidores en redes', 'Los que eligen a los mejores para su grupo', 'Los que nunca se equivocan'], ref='CV 231'),
            dict(p='Para participar de algunos espacios para jóvenes, ¿hace falta asumir todas las enseñanzas de la Iglesia?', ok='No: basta una actitud abierta a dejarse encontrar por la verdad',
                 otras=['Sí, desde el primer día', 'Sí, y además estar confirmado', 'Solo si el coordinador lo aprueba'], ref='CV 234'),
            dict(p='¿Qué pasaje propuso el Sínodo como modelo de la pastoral juvenil?', ok='Los discípulos de Emaús',
                 otras=['La multiplicación de los panes', 'Las bodas de Caná', 'El joven rico'], ref='CV 236-237'),
            dict(p='¿Cómo debe mirar la comunidad a los jóvenes?', ok='Con comprensión, valoración y afecto, sin exigirles una perfección que no responde a su edad',
                 otras=['Con exigencia para que no se desvíen', 'Con distancia para no influir en ellos', 'Con controles frecuentes'], ref='CV 243'),
            dict(p='Según los mismos jóvenes, ¿qué cualidad es «especialmente importante» en un acompañante?', ok='El reconocimiento de su propia humanidad: que es imperfecto y pecador perdonado',
                 otras=['Que nunca muestre sus debilidades', 'Que tenga muchos títulos', 'Que sea mucho mayor que ellos'], ref='CV 246'),
            dict(p='Cuando nos toca ayudar a otro a discernir el camino de su vida, ¿qué es lo primero?', ok='Escuchar', otras=['Dar consejos', 'Corregir', 'Contar la propia experiencia'], ref='CV 291'),
            dict(p='¿Cuáles son las tres sensibilidades de la escucha?', ok='A la persona, discernidora y hacia adelante (hacia dónde quiere ir)',
                 otras=['Paciencia, silencio y oración', 'Mirar, preguntar y corregir', 'Escuchar, juzgar y aconsejar'], ref='CV 292-294'),
            dict(p='¿Cuál es el signo de la escucha atenta a la persona?', ok='El tiempo que le dedico, que el otro sienta que mi tiempo es suyo',
                 otras=['Tomar nota de todo lo que dice', 'Responder rápido a cada mensaje', 'Darle siempre la razón'], ref='CV 292'),
            dict(p='¿Qué hay que hacer con los procesos de cada persona?', ok='Suscitarlos y acompañarlos, no imponer trayectos',
                 otras=['Armar un recetario igual para todos', 'Decidir por ellos lo que les conviene', 'Esperar a que pidan ayuda'], ref='CV 297'),
            dict(p='Para acompañar a otros en este camino, primero necesitás…', ok='Tener el hábito de recorrerlo vos mismo',
                 otras=['Haber terminado un curso de psicología', 'Ser mayor de edad', 'Conocer a la familia del otro'], ref='CV 298'),
            dict(p='Según Christus vivit, la pastoral juvenil debe ser siempre…', ok='Misionera', otras=['Silenciosa', 'Igual que hace veinte años', 'Solo dentro de la parroquia'], ref='CV 240'),
        ]),
]

# Curso que todavía no tiene contenido: aparece como "Próximamente".
PROXIMOS = []

CURSOS.append(dict(
    id='hablar-de-jesus', icono='💬', titulo='¿Cómo hablar de Jesús?',
    resumen='Un taller práctico para hablar de Jesús delante de otros: preparar, empezar, terminar y contar historias.',
    para='Para quienes dan charlas, encuentros, testimonios o misiones.',
    minutos=35,
    lecturas=[dict(texto='Cuadernillo de la cumbre (PDF)', url='docs/academia/cumbre-04-hablar-de-jesus.pdf',
                   guia='Texto propio de la Academia Frassati, basado en el curso «¿Cómo hablar de Jesús?» de Cristian Carman. Los números al margen son los que cita el examen.')],
    preguntas=[
        dict(p='Según el cuadernillo, ¿cuáles son las tres tareas de quien habla delante de otros?', ok='Enseñar, deleitar y conmover',
             otras=['Informar, entretener y convencer', 'Leer, explicar y resumir', 'Saludar, hablar y agradecer'], ref='Cuadernillo, n. 1'),
        dict(p='¿Para qué sirve tener un anecdotario?', ok='Para anotar historias, anécdotas y frases y tener de dónde sacar al preparar una charla',
             otras=['Para escribir la charla palabra por palabra', 'Para anotar los nombres de los que escuchan', 'Para llevar la cuenta de las charlas que diste'], ref='Cuadernillo, n. 3'),
        dict(p='Antes de pensar qué decir, ¿qué conviene preguntarse?', ok='Para qué: cuál es el objetivo de la charla',
             otras=['Cuánta gente va a venir', 'Qué ropa ponerse', 'Qué dijo el orador anterior'], ref='Cuadernillo, n. 4'),
        dict(p='Según el cuadernillo, ¿qué hace que los miedos desaparezcan?', ok='No ponerme yo en el centro',
             otras=['Leer todo de un papel', 'Hablar rápido para terminar antes', 'No mirar nunca a la gente'], ref='Cuadernillo, n. 6'),
        dict(p='¿Qué frase de Juan el Bautista cita el cuadernillo sobre los miedos?', ok='«Es necesario que él crezca y que yo disminuya»',
             otras=['«Preparen el camino del Señor»', '«Yo no soy digno de desatar su sandalia»', '«Este es el Cordero de Dios»'], ref='Cuadernillo, n. 6'),
        dict(p='En el primer paso, buscar las ideas, ¿qué conviene hacer?', ok='Volver al tema un par de veces por día y anotar todo, sin pretender que esté ordenado',
             otras=['Escribir la charla entera de una sola vez', 'Copiar una charla de internet', 'Esperar al día anterior para pensarla'], ref='Cuadernillo, n. 8'),
        dict(p='¿Qué hacer con el contenido que no entra en el tiempo de la charla?', ok='Dejarlo para otra vez: las buenas ideas no envejecen',
             otras=['Decirlo igual, más rápido', 'Pedir más tiempo a los organizadores', 'Ponerlo en una diapositiva llena de texto'], ref='Cuadernillo, n. 10'),
        dict(p='Si practicando en tu casa la charla dura 17 minutos, en vivo…', ok='Va a durar más: unos 25 minutos',
             otras=['Va a durar lo mismo', 'Va a durar menos, porque los nervios aceleran', 'Depende solo del micrófono'], ref='Cuadernillo, n. 10'),
        dict(p='¿Cómo tiene que salir la charla, según el cuadernillo?', ok='Sabida como el Padrenuestro, pero dicha como una oración espontánea',
             otras=['Leída palabra por palabra', 'Improvisada, sin preparar nada', 'Memorizada y recitada sin pausas'], ref='Cuadernillo, n. 11'),
        dict(p='¿Cuáles son los momentos más importantes de una charla?', ok='El principio y el final',
             otras=['La mitad', 'Las preguntas del público', 'Los agradecimientos'], ref='Cuadernillo, n. 12'),
        dict(p='¿Por qué conviene tener el comienzo casi de memoria?', ok='Porque es cuando más nervioso estás y menos podés improvisar',
             otras=['Porque el público no presta atención al principio', 'Porque así se termina antes', 'Porque es la parte más larga'], ref='Cuadernillo, n. 13'),
        dict(p='¿Qué conviene NO hacer al empezar una charla?', ok='Pedir perdón o excusarse por la preparación',
             otras=['Contar una historia', 'Mirar a la gente a los ojos', 'Hacer una pregunta que el público ya se hace'], ref='Cuadernillo, n. 14'),
        dict(p='¿Qué hizo san Pablo en Atenas para anunciar a Jesús?', ok='Partió de lo que ellos buscaban: el altar «Al dios desconocido»',
             otras=['Les reprochó que fueran paganos', 'Les leyó la ley de Moisés', 'Les contó un chiste'], ref='Cuadernillo, n. 20'),
        dict(p='¿Cuál es la regla de oro para terminar una charla?', ok='Cuando termina el contenido, termina la charla',
             otras=['Hay que llegar siempre al tiempo máximo', 'Terminar siempre con una pregunta', 'Avisar tres veces que se está por terminar'], ref='Cuadernillo, n. 22'),
        dict(p='Si te pasaste de tiempo, ¿qué conviene hacer?', ok='No pedir perdón y cerrar bien',
             otras=['Pedir disculpas y seguir', 'Cortar de golpe en la mitad de una idea', 'Saltear el final'], ref='Cuadernillo, n. 23'),
        dict(p='¿Qué conviene hacer antes del último párrafo?', ok='Una pausa, como el pateador antes del penal',
             otras=['Hablar más rápido', 'Decir «para terminar…»', 'Contar una historia nueva'], ref='Cuadernillo, n. 26'),
        dict(p='Según el cuadernillo, ¿por qué Dios eligió contar historias en vez de darnos un manual?', ok='Porque él nos conoce y sabe cómo nos hizo',
             otras=['Porque los manuales no existían', 'Porque las historias son más cortas', 'Porque así nadie las entiende'], ref='Cuadernillo, n. 29'),
        dict(p='¿Qué es una historia sin contenido?', ok='Un paquete vacío: no hay que usar historias de relleno',
             otras=['La mejor forma de empezar', 'Algo que siempre suma', 'Lo que más recuerda la gente'], ref='Cuadernillo, n. 32'),
        dict(p='Si contás una historia inventada, ¿qué tiene que pasar?', ok='Tiene que quedar claro que es inventada',
             otras=['Hay que presentarla como real', 'No se pueden contar historias inventadas', 'Hay que contarla al final'], ref='Cuadernillo, n. 33'),
        dict(p='¿Cómo conviene armar una historia?', ok='De atrás para adelante: pensar primero adónde querés llegar',
             otras=['Empezar a contarla y ver adónde llega', 'Con muchos personajes sin nombre', 'Copiándola tal cual de internet'], ref='Cuadernillo, n. 37'),
        dict(p='¿Qué ayuda a construir la escena de una historia?', ok='Usar los cinco sentidos y detalles concretos',
             otras=['Contarla siempre en tercera persona', 'Evitar todo detalle', 'Hablar más fuerte'], ref='Cuadernillo, n. 38'),
    ]))
