"""Lo que escribimos nosotros en cada cuadernillo de la Academia Frassati.

Cada cumbre tiene:
  intro      Párrafo de "Antes de subir".
  aprender   Lo que vas a aprender (lista).
  leer       Cómo leerlo (lista).
  destacados {n: (frase textual, referencia)}  → se intercala después del párrafo n. La frase tiene que ser TEXTUAL del documento.
  pausas     {n: [preguntas]}  → recuadro "Para detenerse" después del párrafo n.
  cierre     Lista de "Antes del examen" (repaso).
La cumbre 04 no lee un documento oficial: su texto (TEXTO_HABLAR) lo escribimos nosotros a partir del curso
"¿Cómo hablar de Jesús?" de Cristian Carman (apuntes de Santiago Villares).
"""

CUMBRES = {
    'sacramentos': dict(
        numero='01', titulo='Los sacramentos', minutos=40, fuente_txt='textos_compendio.json',
        lectura='Compendio del Catecismo de la Iglesia Católica (2005), preguntas 224 a 350',
        pie='Compendio del Catecismo · 2005',
        credito='Texto del Compendio del Catecismo de la Iglesia Católica (2005), tomado de vatican.va. Las referencias numéricas al Catecismo de cada respuesta se omitieron para facilitar la lectura.',
        intro='Los sacramentos son el modo en que Jesús sigue tocando nuestra vida hoy: nos lava, nos fortalece, nos alimenta, nos perdona, nos cura y nos envía. Esta cumbre recorre los siete, uno por uno, con las preguntas y respuestas del Compendio del Catecismo: qué es cada sacramento, cómo se celebra, quién lo da y qué hace en nosotros.',
        aprender=['Qué es un sacramento y por qué son siete.', 'Cómo se agrupan: iniciación, curación y servicio.',
                  'El signo, el ministro y los efectos de cada uno.', 'Qué es el «carácter» y por qué algunos se reciben una sola vez.'],
        leer=['Es un texto de preguntas y respuestas: leelo por sacramento, de a uno, en dos o tres ratos.',
              'Los números al margen son los del Compendio: el examen los cita para que puedas volver a buscarlos.',
              'Parate en los recuadros «Para detenerse»: son para rezar o charlar en tu grupo.'],
        destacados={229: ('Es Cristo quien actúa en ellos y quien da la gracia que significan.', 'Compendio, 229'),
                     274: ('La Eucaristía es fuente y culmen de toda la vida cristiana.', 'Compendio, 274'),
                     310: ('La paz y la serenidad de conciencia y el consuelo del espíritu.', 'Compendio, 310')},
        pausas={264: ['¿Sabés la fecha de tu Bautismo? ¿Quién te bautizó y quiénes son tus padrinos?', '¿Qué significa para vos pertenecer «para siempre a Cristo»? (263)'],
                270: ['La Confirmación da «una fuerza especial para dar testimonio» (268). ¿Dónde te cuesta más dar testimonio de tu fe?'],
                294: ['¿Cómo me preparo antes de comulgar? ¿Y cómo agradezco después?', '¿Qué cambiaría si viviera la misa del domingo como «fuente y culmen» de mi semana?'],
                312: ['¿Cuándo fue mi última confesión? ¿Qué me frena para volver?'],
                350: ['¿Qué sacramento me falta recibir, o vivir mejor? ¿Qué paso concreto puedo dar?']},
        cierre=['Los siete sacramentos y sus tres grupos (224, 250).', 'Los sacramentos que imprimen carácter (227).',
                'El rito esencial y el ministro de cada uno.', 'Qué es la transubstanciación (283) y qué se requiere para comulgar (291).',
                'Los actos del penitente (303) y el sigilo sacramental (309).']),

    'misa': dict(
        numero='02', titulo='La misa, parte por parte', minutos=35, fuente_txt='textos_igmr.json',
        lectura='Instrucción General del Misal Romano, números 27 a 90',
        pie='Instrucción General del Misal Romano',
        credito='Texto de la Instrucción General del Misal Romano (tercera edición típica), tomado de vatican.va. Se omitieron las notas al pie.',
        intro='La misa no es una sucesión de rezos sueltos: es una sola gran oración con una estructura muy pensada. Esta cumbre recorre la Instrucción General del Misal Romano, el documento que explica qué pasa en cada momento de la celebración y por qué. Después de leerla, cada parte de la misa del domingo va a tener otro sentido.',
        aprender=['Las dos grandes partes de la misa y cómo se unen.', 'Los ritos iniciales, la Liturgia de la Palabra y la Liturgia Eucarística, paso a paso.',
                  'Qué es la Plegaria Eucarística y cuáles son sus partes.', 'El sentido de los gestos, las posturas y el silencio.'],
        leer=['Leelo con una misa en la cabeza: la del domingo pasado o la próxima.', 'Los números al margen son los del documento: el examen los cita.',
              'Parate en los recuadros «Para detenerse»: son para rezar o charlar en tu grupo.'],
        destacados={28: ('Constituyen un solo acto de culto.', 'IGMR, 28'),
                    60: ('La lectura del Evangelio constituye la cumbre de la Liturgia de la Palabra.', 'IGMR, 60'),
                    78: ('En este momento comienza el centro y la cumbre de toda la celebración, esto es, la Plegaria Eucarística.', 'IGMR, 78')},
        pausas={45: ['¿Llego a misa con tiempo para hacer silencio antes de empezar? (45)'],
                54: ['En el acto penitencial pedimos perdón «todos juntos». ¿Qué le querés presentar al Señor al empezar la próxima misa?'],
                71: ['¿Qué lectura o frase de la última misa te acordás? ¿Qué te dijo Dios ahí?', 'En la oración universal rezamos por toda la Iglesia y el mundo. ¿Por quién rezarías vos?'],
                89: ['¿Qué cambia saber que en la fracción del pan «formamos un solo cuerpo» (83) con los que comulgan a tu lado?'],
                90: ['La misa termina con un envío: «para que cada uno regrese a su bien obrar» (90). ¿A qué te envía Dios esta semana?']},
        cierre=['Las dos partes de la misa (28) y los ritos iniciales (46).', 'Cuándo se omite el Gloria (53) y qué se canta en Cuaresma en lugar del Aleluya (62).',
                'Quién puede hacer la homilía (66) y cuándo se reza el Credo (68).', 'Las partes de la Plegaria Eucarística (79), en especial la epíclesis.',
                'El sentido de la fracción del pan (83) y el rito de conclusión (90).']),

    'coordinador': dict(
        numero='03', titulo='¿Cómo ser un buen coordinador?', minutos=45, fuente_txt='textos_cv.json',
        lectura='Christus vivit, del papa Francisco (2019), números 202 a 247 y 291 a 298',
        pie='Christus vivit · Francisco, 2019',
        credito='Texto de la exhortación apostólica Christus vivit (25 de marzo de 2019), tomado de vatican.va. Se omitieron las notas al pie.',
        intro='Coordinar no es dar charlas: es acompañar a otros en su camino hacia Jesús. En Christus vivit el papa Francisco les habla a quienes acompañan a jóvenes y les pide tres cosas: escuchar, acompañar procesos y no dejar nunca de anunciar a Jesús. Esta cumbre recorre el capítulo séptimo, «La pastoral de los jóvenes», y el final del noveno, sobre cómo escuchar.',
        aprender=['Las dos grandes líneas de la pastoral juvenil: la búsqueda y el crecimiento.', 'Por qué toda formación es profundizar el kerygma.',
                  'Qué es una pastoral «popular» y por qué no tiene que ser elitista.', 'Cómo es un buen acompañante y las tres sensibilidades de la escucha.'],
        leer=['Leelo en dos o tres ratos, con lápiz.', 'Los números al margen son los del documento: el examen los cita.',
              'Parate en los recuadros «Para detenerse»: son para rezar o charlar con tu equipo de coordinadores.'],
        destacados={211: ('Es necesario acercarse a los jóvenes con la gramática del amor, no con el proselitismo.', 'Christus vivit, 211'),
                    214: ('Jamás debe sustituirse esta experiencia gozosa de encuentro con el Señor por una suerte de «adoctrinamiento».', 'Christus vivit, 214'),
                    292: ('No es cuestión de cantidad sino de que el otro sienta que mi tiempo es suyo.', 'Christus vivit, 292')},
        pausas={208: ['¿En qué cosas de mi grupo podría dejar más protagonismo a los chicos? (203)'],
                215: ['Pensá en el último encuentro que diste: ¿fue más «contenido» o más «encuentro con Jesús»? (212–214)', '¿Qué espacio tiene el amor fraterno y el servicio en tu grupo? (215)'],
                220: ['¿Tu grupo es un lugar donde alguien que llega solo se siente en casa? ¿Qué podrías cambiar? (216–218)'],
                241: ['¿A quién de tu grupo le cuesta más integrarse? ¿Cómo podrías incluirlo? (231–234)'],
                247: ['Releé las cualidades del acompañante (246). ¿Cuál es tu fuerte? ¿Cuál te falta trabajar?'],
                298: ['¿A quién estás acompañando hoy? ¿Le estás dando tiempo de verdad?', '¿Quién te acompaña a vos en tu camino? (298)']},
        cierre=['Las dos líneas de acción: búsqueda y crecimiento (209).', 'Los dos ejes de toda formación: kerygma y amor fraterno (213).',
                'El modelo de Emaús (236–237) y la pastoral popular (230–234).', 'Las cualidades del acompañante según los jóvenes (246).',
                'Las tres sensibilidades de la escucha (292–294) y acompañar procesos (297).']),

    'hablar-de-jesus': dict(
        numero='04', titulo='¿Cómo hablar de Jesús?', minutos=35, fuente_txt=None,
        lectura='Este cuadernillo (texto propio de la Academia Frassati)',
        pie='Academia Frassati · ¿Cómo hablar de Jesús?',
        credito='Texto de la Academia Frassati basado en los apuntes del curso «¿Cómo hablar de Jesús?» de Cristian Carman. Citas bíblicas de El Libro del Pueblo de Dios. Oración atribuida a santo Tomás de Aquino.',
        intro='A todos nos toca, alguna vez, hablar de Jesús delante de otros: en un encuentro del grupo, en un retiro, en una misión o en una charla con amigos. Esta cumbre es un taller práctico para hacerlo bien: cómo preparar lo que vas a decir, cómo empezar y terminar, y por qué las historias llegan al corazón mejor que cualquier explicación.',
        aprender=['Los hábitos y los pasos para preparar una charla.', 'Cómo empezar y qué no hacer en los primeros segundos.',
                  'Cómo terminar con fuerza, sin estirar ni cortar de golpe.', 'Por qué y cómo contar historias.'],
        leer=['Leelo pensando en la próxima vez que te toque hablar.', 'Los números al margen son de este cuadernillo: el examen los cita.',
              'Parate en los recuadros «Para detenerse» y, si podés, practicá con alguien.'],
        destacados={6: ('Si yo no me pongo en el centro, los miedos desaparecen.', 'n. 6'),
                    22: ('Cuando termina el contenido, termina la charla.', 'n. 22'),
                    31: ('Una historia que te cuentan te puede cambiar la vida.', 'n. 31')},
        pausas={11: ['Pensá en la próxima charla o encuentro que te toca dar. ¿Cuál es su objetivo, en una frase?'],
                20: ['¿Cómo empezaste tu última charla? ¿Caíste en alguno de los «qué no hacer»?'],
                28: ['¿Cómo vas a terminar tu próxima charla? Escribí la última frase.'],
                38: ['¿Qué historia tuya, de un santo o de tu familia podría ayudarte a hablar de Jesús?', 'Contásela a alguien y pedile que te diga qué entendió.']},
        cierre=['Enseñar, deleitar y conmover (1).', 'Los cinco pasos para preparar una charla (8–11).', 'Qué no hacer al empezar (14–17) y al terminar (23–25).',
                'Por qué contar historias (30–33) y sus tres tipos (34–36).', 'Cómo armar una historia: de atrás para adelante y con los cinco sentidos (37–38).']),
}

# ---------------------------------------------------------------------------------------------
# Cumbre 04: texto propio, con números de párrafo para que el examen pueda citarlos.
# ('t', título) o (n, texto). Basado en el curso de Cristian Carman; redactado por la Academia.
TEXTO_HABLAR = [
    ('t', 'Para qué hablamos'),
    (1, 'Cuando hablamos delante de otros tenemos tres tareas: <em>enseñar</em>, <em>deleitar</em> y <em>conmover</em>. Enseñar es que se lleven una idea clara; deleitar, que disfruten escuchando; conmover, que algo se mueva por dentro. Una buena charla sobre Jesús no se queda solo en la primera.'),
    (2, 'No hace falta ser un gran orador. Hace falta prepararse con cariño, como quien prepara un regalo, y animarse. Jesús mismo nos lo pidió: «Vayan por todo el mundo, anuncien la Buena Noticia a toda la creación» (Mc 16,15).'),
    ('t', 'Cinco hábitos de quien habla bien'),
    (3, '<strong>Tener un anecdotario.</strong> Un cuaderno o una nota en el celular donde anotar historias, anécdotas y frases que te llaman la atención. El día que te toque hablar, vas a tener de dónde sacar.'),
    (4, '<strong>Tener siempre un objetivo.</strong> Antes de pensar qué decir, preguntate para qué. Con el objetivo claro es más fácil decidir cómo empezar y qué historias sumar.'),
    (5, '<strong>Mirar cómo hablan otros.</strong> Prestá atención a los recursos de los buenos oradores —un gesto, una pausa, una forma de empezar— y animate a usarlos. Probalos primero en conversaciones de todos los días.'),
    (6, '<strong>Recibir los miedos.</strong> Como san Francisco, que hablaba del «hermano miedo». Mirá si el miedo tiene fundamento: si lo tiene, atacá la causa; si no, dejalo pasar. Y sobre todo: si yo no me pongo en el centro, los miedos desaparecen. «Es necesario que él crezca y que yo disminuya» (Jn 3,30).'),
    (7, '<strong>Rezar antes.</strong> Hablar de Jesús es servirlo a él. Una oración antigua, atribuida a santo Tomás de Aquino, pide: «Instrúyeme en el comienzo, dirígeme en el desarrollo y ayúdame a darle su debido final».'),
    ('t', 'Cinco pasos para preparar una charla'),
    (8, '<strong>Buscar las ideas.</strong> Es el momento creativo: volvé al tema un par de veces por día y anotá todo lo que se te ocurra, sin pretender que esté ordenado.'),
    (9, '<strong>Ordenarlas.</strong> Armá la estructura: un comienzo que conecte con el tema, un desarrollo y un final. Elegí qué va y qué queda afuera.'),
    (10, '<strong>Darle forma y medir el tiempo.</strong> Adaptá el contenido al tiempo que tenés, y no al revés. No sobrecargues: lo que no entra queda para otra vez, porque las buenas ideas no envejecen. Cronometrate practicando: lo que en tu casa dura 17 minutos, en vivo dura 25.'),
    (11, '<strong>Conocer la estructura y decirla.</strong> Sabé el punto por punto de memoria —una hojita ayuda si te ponés nervioso— y practicala frente a alguien que te dé su opinión. Que la sepas como el Padrenuestro, pero que te salga como una oración espontánea. El día de la charla, llegá con tiempo, prepará tu momento de oración y cuidá tu ánimo: lejos de lo que te distrae.'),
    ('t', 'Cómo empezar'),
    (12, 'El principio y el final son los momentos más importantes. En los primeros segundos la gente decide si te va a seguir escuchando, como cuando pasamos videos en el celular: si no engancha, seguimos de largo.'),
    (13, 'Por eso el comienzo conviene tenerlo muy preparado, casi de memoria: es cuando más nervioso estás y menos podés improvisar.'),
    (14, '<strong>No empezar pidiendo perdón.</strong> «Me pidieron que prepare algo, a ver qué sale…» le quita fuerza a todo lo que viene. No hace falta excusarse.'),
    (15, '<strong>No hablar de la preparación.</strong> Al que escucha no le interesa cómo llegaste a la charla ni lo que descartaste: andá directo al punto.'),
    (16, '<strong>No arrancar chocando.</strong> Si tenés que decir algo que duele, primero ponete del lado del otro y después enfrenten juntos el problema.'),
    (17, '<strong>No arrancar con agradecimientos de compromiso.</strong> Si querés agradecer, que sea breve y separado del inicio, o convertilo en algo lindo: una historia en común, una broma sobre la situación.'),
    (18, 'Para ganarte a los que escuchan: mirá a la gente a los ojos, mostrate humano —contar un error propio acerca mucho— y, si el contexto lo permite, hacé reír. Halagar al público solo sirve si la admiración es sincera; si no, suena falso.'),
    (19, 'Algunas formas de llamar la atención: una historia desconcertante que después conectás con el tema, algo gracioso, un objeto que muestra lo que vas a contar —los apuntes de un retiro, las zapatillas gastadas de la peregrinación a Luján— o una pregunta que la gente ya se está haciendo.'),
    (20, 'San Pablo lo hizo en Atenas. Empezó con lo que tenían ellos: «Atenienses, veo que ustedes son, desde todo punto de vista, los más religiosos de todos los hombres. En efecto, mientras me paseaba mirando los monumentos sagrados que ustedes tienen, encontré entre otras cosas un altar con esta inscripción: “Al dios desconocido”. Ahora, yo vengo a anunciarles eso que ustedes adoran sin conocer» (Hch 17,22-23). Partió de su búsqueda para anunciarles a Jesús.'),
    ('t', 'Cómo terminar'),
    (21, 'El final es la frutilla del postre. Si una película termina mal, nos olvidamos de todo lo bueno; si una charla termina bien, la gente se va con eso.'),
    (22, 'Hay que preparar el final tanto como el comienzo. Y una regla de oro: cuando termina el contenido, termina la charla. Guardá algo bueno para el cierre, como en las películas donde la mejor pelea es la última.'),
    (23, '<strong>No estirar.</strong> Arrancás, decís lo que tenés que decir y te callás. Si te pasaste de tiempo, no pidas perdón: cerrá bien.'),
    (24, '<strong>No terminar de golpe.</strong> Que se note el cambio de clima: si cortás de repente, la gente queda descolocada, como cuando una película termina de la nada.'),
    (25, '<strong>No anunciar el final.</strong> Mejor que el «para terminar…» o el «perdón que me extienda» es que el final se sienta solo.'),
    (26, '<strong>Hacer una pausa antes del último párrafo.</strong> Como el pateador antes del penal: un respiro, un gesto, y el tono justo para que todos sepan que llegó el momento.'),
    (27, '<strong>Terminar como empezaste.</strong> Si arrancaste con una historia y la dejaste sin terminar, contá su final al cierre: es una de las formas más lindas de aterrizar.'),
    (28, 'Si vas a dejar una tarea, que sea en el anteúltimo momento, para que el cierre siga siendo el final.'),
    ('t', 'La importancia de las historias'),
    (29, 'Dios podría habernos dado un manual para vivir. Pero eligió contar historias: la Biblia está llena de ellas y la vida misma de Jesús es una historia. Él nos conoce y sabe cómo nos hizo.'),
    (30, 'Lo que más influye son los hechos, no las palabras. Contar un hecho lo hace presente otra vez y hace que llegue más allá de los que lo vivieron: por eso son tan importantes las vidas de los santos y los testimonios.'),
    (31, 'Las historias no vencen: a veces no hacen efecto en el momento, pero vuelven justo cuando las necesitamos. Una historia que te cuentan te puede cambiar la vida.'),
    (32, 'Además, se recuerdan mucho más que las ideas, llegan directo al corazón y hacen que el que habla caiga bien. Pero ojo: una historia sin contenido es un paquete vacío. Que tus historias no sean relleno.'),
    (33, 'Las historias pueden ser propias o ajenas —de tu familia, de un santo, de un amigo—, pero tienen que tener algún vínculo con vos. Si una historia es inventada, que quede claro que lo es.'),
    ('t', 'Tres tipos de historias'),
    (34, '<strong>Para presentarte.</strong> Cuando no te conocen, una anécdota sobre vos —mejor si es divertida— dice quién sos más que cualquier currículum.'),
    (35, '<strong>Para mover a la acción.</strong> Una historia puede animar a dar un paso: confesarse, rezar el rosario, sumarse a una misión. A veces se resume en una frase que queda: «¿cuál es tu arca de Noé?».'),
    (36, '<strong>Para fijar un valor.</strong> El hijo pródigo enseña el perdón mejor que cualquier explicación. Contá cada gesto para que el que escucha lo imagine: si entrás en la imaginación del otro, ganaste.'),
    ('t', 'Cómo armar una historia'),
    (37, '<strong>De atrás para adelante.</strong> Pensá primero adónde querés llegar y reconstruí el camino. Pocos personajes, con nombre, y que cada uno tenga un papel. Contala en el orden justo: como un chiste, si la contás mal, se estropea. Y si no le podés dedicar el tiempo para contarla bien, mejor no la cuentes.'),
    (38, '<strong>Construí la escena con los cinco sentidos.</strong> «Había olor a café», «le agarré la mano arrugada»: los detalles concretos hacen la historia real. Mejor en primera persona que en tercera. Y las emociones: si no las sentís vos, no las transmitís. Volvé a conectar con lo que viviste un rato antes de hablar, sin forzar nada: la gente se da cuenta cuando algo es falso.'),
]
